SELECT * FROM AUTILIS WHERE PRFMEN_0 <> 'Y001'

SELECT * FROM SORDERQ WHERE ITMREF_0 = 'IIH5019'

SELECT * FROM STOALL WHERE ITMREF_0 = 'ICN0057'
SELECT * FROM STOCK	WHERE ITMREF_0 = 'ICN0057'

SELECT * FROM AFONCTION WHERE CODEXT_0 IN ('GESEXS','GESSMR','VXAPT','FUNMAUTR','GESMFG','GESMTK','GESPOH','GESPSH','GESROU','GESSCO','GESSMO','GESSMX','GESSOH','GESSTQ')


SELECT * FROM ATEXTRA WHERE CODFIC_0 = 'AFONCTION' IN ('GESEXS','GESSMR','VXAPT','FUNMAUTR','GESMFG','GESMTK','GESPOH','GESPSH','GESROU','GESSCO','GESSMO','GESSMX','GESSOH','GESSTQ')
SELECT * FROM ATEXTE WHERE NOMZON_0 IN ('GESEXS','GESSMR','VXAPT','FUNMAUTR','GESMFG','GESMTK','GESPOH','GESPSH','GESROU','GESSCO','GESSMO','GESSMX','GESSOH','GESSTQ')
SELECT * FROM ATEXTE WHERE TEXTE_0 = N'AFONCTION'
SELECT * FROM ATEXTE WHERE CLEREC_0 = '门户管理'

SELECT * FROM AFONCTION






