;WITH ABOM 
AS (
	SELECT    N'MVT8108' AS MainBom,
				ITMREF_0 AS N'BOM代码',
				(SELECT ITMDES1_0 FROM ITMMASTER WHERE ITMREF_0 = BOMD.ITMREF_0) AS N'产品名称',
				CPNITMREF_0,
				(SELECT ITMDES1_0 FROM ITMMASTER WHERE ITMREF_0 = BOMD.CPNITMREF_0) AS N'组件名称',
				(SELECT CASE REOCOD_0 WHEN 1 THEN N'无建议' WHEN 2 THEN N'采购' WHEN 3 THEN N'生产' WHEN 4 THEN N'地点间' WHEN 5 THEN N'外协' ELSE N'未知' END FROM ITMFACILIT WHERE ITMREF_0 = BOMD.CPNITMREF_0 AND STOFCY_0 = N'203' ) AS N'属性',
				BOMQTY_0 AS '数量',
				LEL = 1,
				PX = CAST(BOMSEQ_0 AS varbinary)
FROM BOMD 
WHERE ITMREF_0 = N'MVT8108'
UNION ALL 
SELECT N'MVT8108' AS MainBom,
			T1.ITMREF_0,
			(SELECT ITMDES1_0 FROM ITMMASTER WHERE ITMREF_0 = T1.ITMREF_0) AS N'产品名称',
			T1.CPNITMREF_0,
			(SELECT ITMDES1_0 FROM ITMMASTER WHERE ITMREF_0 = T1.CPNITMREF_0) AS N'组件名称',
			(SELECT CASE REOCOD_0 WHEN 1 THEN N'无建议' WHEN 2 THEN N'采购' WHEN 3 THEN N'生产' WHEN 4 THEN N'地点间' WHEN 5 THEN N'外协' ELSE N'未知' END FROM ITMFACILIT WHERE ITMREF_0 = T1.CPNITMREF_0 AND STOFCY_0 = N'203' ) AS N'属性',
			T1.BOMQTY_0,LEL + 1,
			CAST(PX + CAST(BOMSEQ_0 AS varbinary) AS varbinary)
FROM BOMD T1 JOIN ABOM AS T2 ON T1.ITMREF_0 = T2.CPNITMREF_0)
SELECT * FROM ABOM ORDER BY PX



SELECT DEFLOCTYP_0,DEFLOC_0,* FROM ITMFACILIT WHERE ITMREF_0 LIKE 'MZN0774' AND STOFCY_0 = '0101'

UPDATE ITMFACILIT SET DEFLOCTYP_0 = 'SMI',DEFLOC_0 = 'MI1' WHERE ITMREF_0 LIKE 'M%' AND STOFCY_0 = '0101'



SELECT T2.MFGNUM_0,
		T2.ITMREF_0 
FROM MFGITMTRK T1
	LEFT JOIN MFGITM T2 ON T1.MFGNUM_0 = T2.MFGNUM_0 AND T1.MFGLIN_0 = 1000
WHERE T1.MFGNUM_0 IN (SELECT MFGNUM_0 FROM MFGMATTRK GROUP BY (MFGNUM_0)) 
	AND T1.MFGFCY_0 = '0201'
	AND T2.MFGSTA_0 < 4
	AND T2.ITMSTA_0 < 3
	AND T2.MFITRKFLG_0 <5


SELECT T1.MFGNUM_0
FROM MFGITM T1
	LEFT JOIN MFGMATTRK T2 ON T1.MFGNUM_0 = T2.MFGNUM_0
	LEFT JOIN MFGITMTRK T3 ON T1.MFGNUM_0 = T3.MFGNUM_0
WHERE T3.MFGNUM_0 IS NULL
	AND T2.MFGNUM_0 IS NOT NULL
	AND T1.MFGFCY_0 = '0201'
	AND T1.MFGSTA_0 < 4
	AND T1.ITMSTA_0 < 3
	AND T1.MFITRKFLG_0 <5
	AND T1.MFGLIN_0 = 1000
GROUP BY T1.MFGNUM_0

DELETE FROM ZTSDELIVERYD WHERE SOHNUM_0 = '0101SOH17060102' AND ITMREF_0 = 'IZF0045'