--采购端物料短缺


--SELECT * FROM MFGMAT
--SELECT * FROM MFGHEAD
--SELECT * FROM MFGITM
--SELECT * FROM ITMMASTER
--SELECT * FROM ITMFACILIT
--SELECT * FROM ATEXTE WHERE LANGUE_0 = 'CHI' AND ZONE_0 = ''
--SELECT * FROM APLSTD WHERE LANCHP_0 = 250 AND LAN_0 = 'CHI'
--SELECT * FROM STOCK
--SELECT * FROM SORDERQ WHERE ITMREF_0 = 'IHQ0700'

--SELECT POHNUM_0,POHFCY_0,ITMREF_0,QTYSTU_0 FROM PORDERQ WHERE LINSTA_0 <> 3 AND LINCLEFLG_0 = 1 AND ITMREF_0 = 'IHQ0700' GROUP BY POHFCY_0,ITMREF_0
--S

--SELECT T1.ITMREF_0,
--		T1.MFGFCY_0,
--		T4.ITMDES1_0,
--		T3.LANMES_0,
--		T4.STU_0,
--		T5.QTYSTU_0,
--		T6.QTYSTU_0,
--		T7.QTY_0
--FROM (SELECT MFGFCY_0,ITMREF_0 FROM MFGMAT GROUP BY ITMREF_0) T1
--	LEFT JOIN ITMFACILIT T2 ON T1.MFGFCY_0 = T2.STOFCY_0 AND T1.ITMREF_0 = T2.ITMREF_0
--	LEFT JOIN APLSTD T3 ON T2.REOCOD_0 = T3.LANNUM_0 AND T3.LANCHP_0 = '250' AND LAN_0 = 'CHI'
--	LEFT JOIN ITMMASTER T4 ON T1.ITMREF_0 = T4.ITMREF_0
--	LEFT JOIN (SELECT STOFCY_0,ITMREF_0,SUM(QTYSTU_0) QTYSTU_0 FROM STOCK WHERE STA_0 = 'A' GROUP BY STOFCY_0,ITMREF_0) T5 ON T1.MFGFCY_0 = T5.STOFCY_0 AND T1.ITMREF_0 = T5.ITMREF_0
--	LEFT JOIN (SELECT POHFCY_0,ITMREF_0,SUM(QTYSTU_0) QTYSTU_0 FROM PORDERQ WHERE LINSTA_0 <> 3 AND LINCLEFLG_0 = 1 GROUP BY POHFCY_0,ITMREF_0) T6 ON T1.MFGFCY_0 = T6.POHFCY_0 AND T1.ITMREF_0 = T6.ITMREF_0
--	LEFT JOIN (SELECT SALFCY_0,ITMREF_0,(SUM(QTY_0)-SUM(DLVQTY_0)) QTY_0 FROM SORDERQ WHERE SALFCY_0 <> '0101' AND SOQSTA_0 <> 3 AND DEMSTA_0 <> 4 GROUP BY SALFCY_0,ITMREF_0 ) T7 ON T1.MFGFCY_0 = T7.SALFCY_0 AND T1.ITMREF_0 = T7.ITMREF_0
--ORDER BY T1.ITMREF_0,T1.MFGFCY_0

SELECT T1.STOFCY_0 N'事业部',
		T1.ITMREF_0 N'物料代码',
		T6.ITMDES1_0 N'物料名称',
		T5.LANMES_0 N'物料属性',
		T6.STU_0 N'单位',
		ISNULL(T2.QTYSTU_0,0)  N'库存数量',
		ISNULL(T3.QTYSTU_0 ,0) N'预计入库量',
		ISNULL(T4.QTY_0,0)  N'已分配量'
FROM ITMFACILIT T1
	LEFT JOIN (SELECT STOFCY_0,ITMREF_0,SUM(QTYSTU_0) QTYSTU_0 FROM STOCK WHERE STA_0 = 'A' GROUP BY STOFCY_0,ITMREF_0) T2 ON T1.ITMREF_0 = T2.ITMREF_0 AND T1.STOFCY_0 = T2.STOFCY_0
	LEFT JOIN (SELECT POHFCY_0,ITMREF_0,SUM(QTYSTU_0) QTYSTU_0 FROM PORDERQ WHERE LINSTA_0 <> 3 AND LINCLEFLG_0 = 1 GROUP BY POHFCY_0,ITMREF_0) T3 ON T1.ITMREF_0 = T3.ITMREF_0 AND T1.STOFCY_0 = T3.POHFCY_0
	LEFT JOIN (SELECT T3.SALFCY_0,	T3.ITMREF_0,SUM(T3.QTY_0) QTY_0 FROM(SELECT SALFCY_0,ITMREF_0,QTY_0 - DLVQTY_0 QTY_0 FROM SORDERQ WHERE SOQSTA_0 <> 3 AND DEMSTA_0 <> 4 UNION SELECT T1.MFGFCY_0 SALFCY_0,T1.ITMREF_0,(T1.RETQTY_0 - T1.ALLQTY_0) QTY_0 FROM MFGMAT T1 LEFT JOIN MFGHEAD T2 ON T1.MFGNUM_0 = T2.MFGNUM_0 WHERE T2.MFGSTA_0 <> 4 ) T3 GROUP BY T3.ITMREF_0,T3.SALFCY_0) T4 ON T1.ITMREF_0 = T4.ITMREF_0 AND T1.STOFCY_0 = T4.SALFCY_0
	LEFT JOIN APLSTD T5 ON T1.REOCOD_0 = T5.LANNUM_0 AND T5.LANCHP_0 = '250' AND T5.LAN_0 = 'CHI'
	LEFT JOIN ITMMASTER T6 ON T1.ITMREF_0 = T6.ITMREF_0
WHERE T1.ITMREF_0 = 'IGZ0662' 
	AND	(T2.QTYSTU_0 IS NOT NULL
	OR T3.QTYSTU_0 IS NOT NULL
	OR T4.QTY_0 IS NOT NULL)

ORDER BY T1.STOFCY_0,T1.ITMREF_0







