	(SELECT BOMD.ITMREF_0,LEL = 1,
	(SELECT ITMDES1_0 FROM ITMMASTER WHERE ITMREF_0 = BOMD.ITMREF_0) ITMDES1_0,
	(SELECT STU_0 FROM ITMMASTER WHERE ITMREF_0 = BOMD.ITMREF_0) STU_0,
	CPNITMREF_0,
	(SELECT ITMDES1_0 FROM ITMMASTER WHERE ITMREF_0 = BOMD.CPNITMREF_0) ITMDES1_0, 
	(SELECT B2.LANMES_0 FROM ITMFACILIT B1,APLSTD B2 WHERE B1.ITMREF_0 = BOMD.CPNITMREF_0 AND B1.STOFCY_0 = N'0203' AND B1.REOCOD_0 = B2.LANNUM_0 AND B2.LANCHP_0 = 250 AND B2.LAN_0 = N'CHI' ) REOCOD_0, 
	BOMSTUCOE_0,
	BOMQTY_0
FROM BOMD 
WHERE BOMD.ITMREF_0 = N'IVB1048-GW')