SELECT T1.SDHNUM_0 AS N'发货单号',
		  T1.SOHNUM_0 AS N'销售订单号',
		  (T1.SOPLIN_0/1000) AS N'销售订单行号',
		  T4.XSOHNUM_0 AS N'事业部订单号',
		  T3.BPCNAM_0 AS N'客户名称',
		  T1.ITMREF_0 AS N'产品名称',
		  T1.QTY_0 AS N'产品数量',
		  T1.GROPRI_0 AS N'产品单价',
		  (T1.QTY_0 * T1.GROPRI_0 * CHGRAT_0) AS N'换算汇率后的金额', 
		  T2.CUR_0 AS N'币种',
		  T2.CHGRAT_0 AS N'汇率',
		  T1.CREUSR_0 AS N'制单人',
		  T1.REP1_0 AS N'业务代表',
		  (CASE T2.CFMFLG_0 WHEN 1 THEN N'否' WHEN 2 THEN N'是' END) AS N'审核标志',
		  T1.CREDAT_0 AS N'制单日期',
		  T1.NETPRINOT_0 AS N'不含税净价',
		  T1.NETPRIATI_0 AS N'含税净价',
		  T1.PFM_0 AS N'利润',
		  T1.CPRPRI_0 AS N'成本价'
FROM SDELIVERYD T1
 LEFT JOIN SDELIVERY T2 ON T1.SDHNUM_0 = T2.SDHNUM_0
 LEFT JOIN BPCUSTOMER T3 ON T1.BPCORD_0 = T3.BPCNUM_0
 LEFT JOIN ZSOYN T4 ON T1.SOHNUM_0 = T4.SOHNUM_0 AND T1.SOPLIN_0 = T4.SOPLIN_0
WHERE T1.STOFCY_0 = '0101'



SELECT * FROM SDELIVERYD WHERE SDHNUM_0 = '0101SDH17070480'


SELECT * FROM MFGITMTRK WHERE ITMREF_0 = 'IVU3761-00'