 SELECT "T3"."SOHNUM_0", 
		"T3"."ITMREF_0", 
		"ITMMASTER"."ITMDES1_0", 
		"T3"."QTY_0", 
		"SORDER"."SOHNUM_0",
		 "T3"."DEMDLVDAT_0", 
		 "T3"."ZRMK_0",
		  "T3"."FMINUM_0", 
		  "SORDER"."BPCNAM_0", 
		  "SORDER"."BPCORD_0",
		   "T1"."SOHNUM_0",
			"T1"."STOFCY_0", 
			"T1"."SALFCY_0",
			"SORDER"."ORDDAT_0", 
			"T3"."ZCUSNUM_0", 
			"SORDER"."ZREMARK_0", 
			"T1"."CREDAT_0", 
			"T1"."SOPLIN_0", 
			"ITMFACILIT"."REOCOD_0"
 FROM   (((("x3v7sql"."INNO"."SORDERQ" "T1" 
	LEFT OUTER JOIN "x3v7sql"."INNO"."PORDERQ" "T2" ON ("T1"."POHNUM_0"="T2"."POHNUM_0") 
															AND ("T1"."POPLIN_0"="T2"."POPLIN_0")) 
	LEFT OUTER JOIN "x3v7sql"."INNO"."SORDERQ" "T3" ON ("T2"."POHNUM_0"="T3"."FMINUM_0") 
															AND ("T2"."POPLIN_0"="T3"."FMILIN_0")) 
	INNER JOIN "x3v7sql"."INNO"."ITMFACILIT" "ITMFACILIT" ON ("T3"."SALFCY_0"="ITMFACILIT"."STOFCY_0") 
															AND ("T3"."ITMREF_0"="ITMFACILIT"."ITMREF_0")) 
	LEFT OUTER JOIN "x3v7sql"."INNO"."ITMMASTER" "ITMMASTER" ON "T3"."ITMREF_0"="ITMMASTER"."ITMREF_0") 
	LEFT OUTER JOIN "x3v7sql"."INNO"."SORDER" "SORDER" ON "T3"."SOHNUM_0"="SORDER"."SOHNUM_0"
 WHERE  ("T1"."CREDAT_0">={ts '2017-01-01 00:00:00'} 
		 AND "T1"."CREDAT_0"<{ts '2017-07-21 00:00:00'}) 
		 AND "T1"."SOHNUM_0"=N'0201SOH17030230' 
		 AND "ITMFACILIT"."REOCOD_0"<>3
 ORDER BY "T3"."SOHNUM_0", "T3"."FMINUM_0"
 

SELECT T2.SOHNUM_0,
		T1.ITMREF_0,
		T3.ITMDES1_0,
		T1.QTY_0,
		T1.SOHNUM_0,
		T2.POHNUM_0,
		T1.DEMDLVDAT_0,
		T1.ZRMK_0,
		T2.BPCNAM_0,
		T2.BPCORD_0,
		T1.SALFCY_0,
		T1.ORDDAT_0,
		T5.ZREMARK_0,
		T1.CREDAT_0
FROM SORDERQ T1
	LEFT JOIN ZSOYN T2 ON T1.SOHNUM_0 = T2.XSOHNUM_0
						AND T1.SOPLIN_0 = T2.XSOPLIN_0
	LEFT JOIN ITMMASTER T3 ON T1.ITMREF_0 = T3.ITMREF_0
	LEFT JOIN ITMFACILIT T4 ON T1.ITMREF_0 = T4.ITMREF_0
							AND T1.SALFCY_0 = T4.STOFCY_0
	LEFT JOIN SORDER T5 ON T2.SOHNUM_0 = T5.SOHNUM_0
WHERE T4.REOCOD_0 <> 3

