--SELECT * FROM STOCK
--SELECT * FROM PORDERQ
--SELECT * FROM ITMMASTER
--SELECT * FROM ITMFACILIT


--SELECT ITMREF_0,SUM(QTYPCU_0) QTYPCU_0 FROM STOCK GROUP BY ITMREF_0
--SELECT ITMREF_0,POHFCY_0,SUM(QTYUOM_0) QTYUOM_0 FROM PORDERQ GROUP BY ITMREF_0,POHFCY_0

SELECT T3.*,
		T4.ITMDES1_0,
		T6.LANMES_0,
		T4.STU_0
FROM
	(SELECT (CASE WHEN T1.ITMREF_0 IS NULL AND T2.ITMREF_0 IS NULL AND T7.ITMREF_0 IS NULL
				  THEN T8.ITMREF_0
				  WHEN T1.ITMREF_0 IS NULL AND T2.ITMREF_0 IS NULL 
				  THEN T7.ITMREF_0 
				  WHEN T1.ITMREF_0 IS NULL AND T7.ITMREF_0 IS NULL 
				  THEN T2.ITMREF_0 
				  ELSE T1.ITMREF_0 
				  END) ITMREF_0,
			T1.STOFCY_0,
			T1.QTYPCU_0,
			T2.POHFCY_0,
			T2.QTYUOM_0,
			T7.SALFCY_0,
			T7.SALQTY_0,
			T8.MFGFCY_0,
			T8.MFGQTY_0
	FROM (SELECT ITMREF_0,STOFCY_0,SUM(QTYPCU_0) QTYPCU_0 FROM STOCK GROUP BY ITMREF_0,STOFCY_0) T1
		FULL JOIN (SELECT ITMREF_0,POHFCY_0,SUM(QTYUOM_0 - RCPQTYSTU_0) QTYUOM_0 FROM PORDERQ GROUP BY ITMREF_0,POHFCY_0) T2 ON T1.ITMREF_0 = T2.ITMREF_0 AND T1.STOFCY_0 = T2.POHFCY_0
		FULL JOIN (SELECT ITMREF_0,SALFCY_0,SUM(QTY_0 - DLVQTY_0) SALQTY_0 FROM SORDERQ GROUP BY ITMREF_0,SALFCY_0) T7 ON T1.ITMREF_0 = T7.ITMREF_0 AND T1.STOFCY_0 = T7.SALFCY_0 AND T2.ITMREF_0 = T7.ITMREF_0 AND T2.POHFCY_0 = T7.SALFCY_0
		FULL JOIN (SELECT ITMREF_0,MFGFCY_0,SUM(RETQTY_0) MFGQTY_0 FROM MFGMAT GROUP BY ITMREF_0,MFGFCY_0) T8 ON T1.ITMREF_0 = T8.ITMREF_0 AND T1.STOFCY_0 = T8.MFGFCY_0 AND T2.ITMREF_0 = T8.ITMREF_0 AND T2.POHFCY_0 = T8.MFGFCY_0
	) T3 
	LEFT JOIN ITMMASTER T4 ON T3.ITMREF_0 = T4.ITMREF_0
	LEFT JOIN ITMFACILIT T5 ON T3.ITMREF_0 = T5.ITMREF_0 AND T3.STOFCY_0 = T5.STOFCY_0
	LEFT JOIN (SELECT LANMES_0,LANNUM_0 FROM APLSTD WHERE LANCHP_0 = 250 AND LAN_0 = N'CHI') T6 ON T5.REOCOD_0 = T6.LANNUM_0
ORDER BY T3.STOFCY_0,T3.ITMREF_0


