SELECT *
FROM (
		SELECT T1.ITMREF_0,
				ISNULL(T1.QTYPCU_0,0) QTY_0
		FROM SMVTD T1 LEFT JOIN SMVTH T2 ON T2.VCRNUM_0 = T1.VCRNUM_0 
		WHERE T2.TRSCOD_0 = 'R02'
			AND T1.CREUSR_0 = 'ALAN'
			AND T1.CREDAT_0 >= '2017-05-20'
			AND T2.STOFCY_0 = '0203'
		GROUP BY T1.ITMREF_0,T1.QTYPCU_0
		)
UNION ALL (
				(SELECT A.ITMREF_0 ITMREF_0,
				ISNULL(SUM(B.CPLQTY_0 * (A.RETQTY_0/B.EXTQTY_0) - A.USEQTY_0),0) QTY_0
				 FROM MFGMAT A,MFGITM B 
				 WHERE (A.RETQTY_0 - A.USEQTY_0) <> 0 
					 AND A.MATSTA_0 = 3 
					 AND A.MFGNUM_0 = B.MFGNUM_0 
					 AND B.MFGLIN_0 = 1000
					 AND A.MFGFCY_0 = '0203'
				 GROUP BY A.ITMREF_0,(B.CPLQTY_0 * (A.RETQTY_0/B.EXTQTY_0) - A.USEQTY_0))
GROUP BY B.ITMREF_0,B.QTY_0
