SELECT  T1.CREDAT_0 N'订单日期',
		T1.SOHNUM_0 N'销售订单号',
		T2.BPCNAM_0 N'客户名称',
		T1.ITMREF_0 N'产品编码',
		T3.ITMDES1_0 N'产品名称',
		T1.ZCUSNUM_0 N'客户订单号',
		T1.QTY_0 N'销售订单数量',
		T4.QTY_0 N'发货数量',
		(CASE T5.CFMFLG_0 WHEN 1 THEN N'未审核' WHEN 2 THEN N'已审核' END) N'发货状态',
		T6.QTY_0 N'发票数量',
		T7.GROPRI_0 N'无税单价',
		T2.CUR_0 N'币种',
		T7.GROPRI_0 * T1.QTY_0 N'原币未税金额',
		(CASE WHEN T2.CUR_0  = N'CNY' THEN T7.GROPRI_0 * T1.QTY_0 ELSE T7.GROPRI_0 * T1.QTY_0 * T2.CHGRAT_0 END) N'外币未税金额',
		T2.CHGRAT_0 N'汇率',
		T8.BPRNAM_0 N'销售代表',
		T9.NOMUSR_0 N'销售订单创建用户'
FROM SORDERQ T1
	LEFT JOIN SORDER T2 ON T1.SOHNUM_0 = T2.SOHNUM_0
	LEFT JOIN ITMMASTER T3 ON T1.ITMREF_0 = T3.ITMREF_0
	LEFT JOIN (SELECT SOHNUM_0,SOPLIN_0,ITMREF_0,SUM(QTY_0) QTY_0 FROM SDELIVERYD GROUP BY SOHNUM_0, SOPLIN_0,ITMREF_0) T4 ON T1.SOHNUM_0 = T4.SOHNUM_0 AND T1.SOPLIN_0 = T4.SOPLIN_0
	LEFT JOIN SDELIVERY T5 ON T1.SDHNUM_0 = T5.SDHNUM_0
	LEFT JOIN (SELECT SOHNUM_0,SOPLIN_0,ITMREF_0,SUM(QTY_0) QTY_0 FROM SINVOICED GROUP BY SOHNUM_0, SOPLIN_0,ITMREF_0) T6 ON T1.SOHNUM_0 = T6.SOHNUM_0 AND T1.SOPLIN_0 = T6.SOPLIN_0
	LEFT JOIN SORDERP T7 ON T1.SOHNUM_0 = T7.SOHNUM_0 AND T1.SOPLIN_0 = T7.SOPLIN_0
	LEFT JOIN BPARTNER T8 ON T2.REP_0 = T8.BPRNUM_0
	LEFT JOIN AUTILIS T9 ON T1.CREUSR_0 = T9.USR_0
WHERE T1.SALFCY_0 = '0101'
	ORDER BY T1.SOHNUM_0

--SELECT * FROM SINVOICED