SELECT T1.POHNUM_0,
		T1.BPSNUM_0,
		T1.ITMREF_0,
		T1.QTYPUU_0,
		T1.RCPQTYPUU_0
FROM PORDERQ T1
WHERE T1.POHFCY_0 <> '0101'
	AND (CONVERT(VARCHAR(10),MONTH(T1.EXTRCPDAT_0),120) = (CONVERT(VARCHAR(10),MONTH(GETDATE()) - 1,120)) 
			OR CONVERT(VARCHAR(10),MONTH(T1.ZRCPDAT_0),120) = (CONVERT(VARCHAR(10),MONTH(GETDATE()) - 1,120))) 
	AND T1.QTYPUU_0 > T1.RCPQTYPUU_0

SELECT MONTH(GETDATE())

SELECT * FROM ITMBPS WHERE  = MIN(PIO_0)¡¢

SELECT ITMREF_0,COUNT(ITMREF_0) FROM ITMBPS GROUP BY ITMREF_0 HAVING COUNT(ITMREF_0) > 1

SELECT T1.ITMREF_0,
		T1.BPSNUM_0
FROM ITMBPS T1
LEFT JOIN (SELECT ITMREF_0,MIN(PIO_0) PIO_0 FROM ITMBPS WHERE BPSNUM_0 LIKE 'YN-%' GROUP BY ITMREF_0) T2 ON T1.ITMREF_0 = T2.ITMREF_0 AND T1.PIO_0 = T2.PIO_0

SELECT * FROM ZSOYN1