SELECT A.MFGFCY_0,
		CASE WHEN B.ITMSTA_0 =3 THEN N'结束' ELSE N'未结束' END AS 状态,
		E.TRKLAST_0 上次追踪日,
		A.MFGNUM_0,
		B.ITMREF_0 成品编码,
		C.ITMDES1_0,
		B.EXTQTY_0 成品计划数,
		B.CPLQTY_0 完工入库,
		A.ITMREF_0 组件,
		G.LANMES_0,
		D.ITMDES1_0,
		F.LANMES_0 建议类型,
		A.RETQTY_0 需求数,
		A.BOMQTY_0*B.CPLQTY_0 已入库需求数,
		A.USEQTY_0 领用数   
FROM MFGMAT A
	INNER JOIN MFGITM B ON A.MFGNUM_0 =B.MFGNUM_0
	INNER JOIN ITMMASTER  C ON C.ITMREF_0=B.ITMREF_0
	INNER JOIN ITMMASTER  D ON A.ITMREF_0=D.ITMREF_0
	INNER JOIN MFGHEAD E ON A.MFGNUM_0=E.MFGNUM_0 
	INNER JOIN (
					SELECT STOFCY_0,
							ITMREF_0,
							REOCOD_0,
							B.LANMES_0 
					FROM ITMFACILIT A
						INNER JOIN APLSTD B ON A.REOCOD_0=B.LANNUM_0 AND  B.LANCHP_0=250 AND B.LAN_0='CHI'
					) F ON A.ITMREF_0= F.ITMREF_0 AND A.MFGFCY_0= F.STOFCY_0
	LEFT JOIN APLSTD G ON A.MATSTA_0 = G.LANNUM_0 AND LAN_0 = 'CHI' AND LANCHP_0 = '363'
WHERE  E.MFGSTA_0=4 
	AND A.RETQTY_0 - A.USEQTY_0 >0