--SELECT * FROM SORDERP	
--SELECT * FROM SORDER
--SELECT * FROM SINVOICED
--SELECT * FROM PAYMENTD



SELECT T1.CREDAT_0,
		T1.SOHNUM_0,
		T1.ITMREF_0,
		T3.QTY_0,
		T2.NUM_0,
		T4.ZREMARK_0,
		T3.ZRMK_0,
		T5.NOMUSR_0
FROM SORDERP T1
	LEFT JOIN SINVOICED T2 ON T1.SOHNUM_0 = T2.SOHNUM_0 AND T1.SOPLIN_0 = T2.SOPLIN_0
	LEFT JOIN SORDERQ T3 ON T1.SOHNUM_0 = T3.SOHNUM_0 AND T1.SOPLIN_0 = T3.SOPLIN_0
	LEFT JOIN SORDER T4 ON T1.SOHNUM_0 = T4.SOHNUM_0
	LEFT JOIN AUTILIS T5 ON T1.CREUSR_0 = T5.USR_0
WHERE T1.BPCORD_0 = 'ZZ-RUS-2151'