SELECT T1.MFGNUM_0,
		T1.ITMREF_0,
		T2.ITMDES1_0,
		T1.RETQTY_0,
		T1.STU_0,
		(CASE T4.MFGSTA_0 
			WHEN 1 THEN N'确认的'
			WHEN 2 THEN N'计划的'
			WHEN 3 THEN N'建议的'
			WHEN 4 THEN N'关闭的'
		END) AS STA,
		T1.CREDAT_0
FROM MFGMAT T1
	LEFT JOIN ITMMASTER T2 ON T1.ITMREF_0 = T2.ITMREF_0
	LEFT JOIN ITMFACILIT T3 ON T1.ITMREF_0 = T3.ITMREF_0
	LEFT JOIN MFGHEAD T4 ON T1.MFGNUM_0 = T4.MFGNUM_0
WHERE T1.MFGFCY_0 = '0202' AND T3.REOCOD_0 = 2
ORDER BY MFGNUM_0 

SELECT * FROM MFGMAT WHERE MFGSTA_0 = 4
SELECT * FROM BOM

SELECT * FROM ORDERS WHERE WIPSTA_0 = 3 AND STOFCY_0 = '0202'

SELECT * FROM SORDER WHERE SALFCY_0 <> '0101' YBPCSHO_0
SELECT * FROM MFGMAT
SELECT * FROM MFGITM
SELECT	T1.WIPNUM_0,
		T1.ITMREF_0,
		T2.ITMDES1_0,
		T1.EXTQTY_0,
		T2.STU_0,
		T1.WIPSTA_0,
		T1.CREDAT_0
FROM ORDERS T1
	LEFT JOIN ITMMASTER T2 ON T1.ITMREF_0 = T2.ITMREF_0
WHERE WIPSTA_0 = 3 AND STOFCY_0 = '0202'
ORDER BY T1.WIPNUM_0










