-- SELECT * FROM SORDERQ WHERE SOHNUM_0 = '0101SOH16110001'
-- SELECT * FROM SORDERP
-- SELECT * FROM AUTILIS
-- SELECT * FROM BPCUSTOMER
-- SELECT * FROM ITMBPC
-- SELECT * FROM ZSOYN



--SELECT T1.SOHNUM_0 AS N'销售订单',
--		T1.SOPLIN_0 / 1000 AS N'行号',
--		T1.ITMREF_0 AS N'产品',
--		T2.ITMDES_0 AS N'产品名称',
--		T1.BPCORD_0 AS N'客户',
--		(SELECT BPCNAM_0 FROM BPCUSTOMER WHERE BPCNUM_0 = T1.BPCORD_0) AS N'客户名称',
--		T1.UPDDATTIM_0 AS N'订单日期',
--		T1.CREDATTIM_0 AS N'创建日期',
--		T1.SHIDAT_0 AS N'交期',
--		T1.QTY_0 AS N'数量',
--		T1.DLVQTY_0 AS N'已发货日期',
--		T1.INVQTY_0 AS N'已开票数量',
--		T2.NETPRI_0 AS N'单价',
--		(T1.QTY_0 * T2.NETPRI_0) AS N'金额',
--		T6.CUR_0 AS N'币种',
--		T1.ZRMK_0 AS N'备注',
--		T1.ZCUSNUM_0 AS N'客户订单号',
--		T3.NOMUSR_0 AS N'创建用户',
--		T1.FMI_0 AS N'发货方式',
--		T4.ITMDESBPC_0 AS N'客户产品号',
--		T5.XSOHNUM_0 AS N'内部订单号',
--		T5.XSOPLIN_0 / 1000 AS N'内部订单行号'
--FROM SORDERQ T1
--	LEFT JOIN SORDERP T2 ON T1.SOHNUM_0 = T2.SOHNUM_0 AND T1.SOPLIN_0 = T2.SOPLIN_0
--	LEFT JOIN AUTILIS T3 ON T1.CREUSR_0 = T3.USR_0
--	LEFT JOIN ITMBPC T4 ON T1.ITMREF_0 = T4.ITMREF_0
--	LEFT JOIN ZSOYN T5 ON T1.SOHNUM_0 = T5.SOHNUM_0 AND T1.SOPLIN_0 = T5.SOPLIN_0
--	LEFT JOIN SORDER T6 ON T1.SOHNUM_0 = T6.SOHNUM_0
--ORDER BY T5.SOHNUM_0,T5.XSOPLIN_0

-- SELECT * FROM ITMMASTER


--SELECT T1.ITMREF_0 AS N'产品',
--		T1.ITMDES1_0 AS N'产品名称',
--		T1.STU_0 AS N'单位',
--		(CASE T1.TSICOD_0 WHEN 3 THEN N'PLASMA' END) AS 统计组,
--		(CASE T1.TSICOD_1 WHEN 2 THEN N'机加工车间' ELSE N'组装车间' END) AS 统计组1
--FROM ITMMASTER T1
--WHERE T1.TSICOD_0 = 3


-- SELECT * FROM MFGMATTRK WHERE ITMREF_0 = N'XXX0002'

--SELECT T1.MFGNUM_0 AS N'工单号',
--		T1.MFGTRKNUM_0 AS N'追踪号',
--		T1.ITMREF_0 AS N'产品',
--		T1.STU_0 AS N'单位',
--		T1.UOMCPLQTY_0 AS N'数量',
--		T1.CREDATTIM_0 AS N'日期'
--FROM MFGITMTRK T1
--WHERE T1.ITMREF_0 IN (N'XXX0000',N'XXX0001',N'XXX0002')





--SELECT T1.MFGNUM_0 AS N'工单号',
--		T1.ITMREF_0 AS N'产品编码',
--		T2.ITMDES1_0 AS N'产品名称',
--		CASE T1.MFGSTA_0 WHEN 1 THEN N'确认' WHEN 2 THEN N'计划' WHEN 3 THEN N'建议' END AS N'工单状态',
--		T1.STU_0 AS N'单位',
--		T1.BOMQTY_0 AS N'单位用量',
--		T1.RETQTY_0 AS N'需求数量',
--		T1.USEQTY_0 AS N'已消耗数量',
--		T1.ALLQTY_0 AS N'已指派数量',
--		T1.SHTQTY_0 AS N'短缺数量',
--		T1.YREQQTY_0 AS N'已申请数量'
--FROM MFGMAT T1
--	LEFT JOIN ITMMASTER T2 ON T1.ITMREF_0 = T2.ITMREF_0
--WHERE MFGFCY_0 = '0202' 
--	AND MFGSTA_0 <> '4' 
--	AND T1.RETQTY_0 <> T1.ALLQTY_0
--	AND T1.YREQQTY_0 > 0
--ORDER BY MFGNUM_0


--SELECT * FROM PRECEIPTD WHERE PTHNUM_0 = '0201REC17010029'

--SELECT * FROM SCHGD WHERE ITMREF_0 = 'IZT0084' AND LOT_0 = 'LO170102010073'

--SELECT * FROM STOCK WHERE LOT_0 = 'LO170102010073'
--SELECT * FROM STOCK WHERE ITMREF_0 = 'IZT0084'
--SELECT * FROM STOJOU WHERE ITMREF_0 = 'IZT0084' AND QTYPCU_0 = 11400

-- SELECT MFMTRKFLG_0,* FROM MFGMAT WHERE MFMTRKFLG_0 <> 1 AND MFGFCY_0 = '0202'

SELECT T1.MFGNUM_0 AS N'工单号',
		T1.ITMREF_0 AS N'产品编码',
		T2.ITMDES1_0 AS N'产品名称',
		CASE T1.MFGSTA_0 WHEN 1 THEN N'确认' WHEN 2 THEN N'计划' WHEN 3 THEN N'建议' END AS N'工单状态',
		T1.STU_0 AS N'单位',
		T1.BOMQTY_0 AS N'单位用量',
		T1.RETQTY_0 AS N'需求数量',
		T1.USEQTY_0 AS N'已消耗数量',
		T1.ALLQTY_0 AS N'已指派数量',
		T1.SHTQTY_0 AS N'短缺数量',
		T1.YREQQTY_0 AS N'已申请数量'
FROM MFGMAT T1
	LEFT JOIN ITMMASTER T2 ON T1.ITMREF_0 = T2.ITMREF_0
WHERE MFMTRKFLG_0 <> 1 
	AND MFGFCY_0 = '0202'


SELECT * FROM SDELIVERYD WHERE 

SELECT SOHNUM_0 FROM SORDERQ  WHERE  SDHNUM_0 = '' AND SALFCY_0 <> '0101' GROUP BY SOHNUM_0

SELECT SDH

























































