SELECT FMINUM_0,POPLIN_0,* FROM SORDERQ WHERE POHNUM_0 = '' AND FMI_0 <> 1
SELECT * FROM ZSOYN

SELECT * FROM 

SELECT POHNUM_0,* FROM SORDERQ WHERE SOHNUM_0 = '0101SOH17020012'

SELECT SOHNUM_0,* FROM PORDERQ WHERE POHFCY_0 = '0101'

SELECT * FROM PORDERQ WHERE SOHNUM_0 IN (SELECT SOHNUM_0 FROM SORDERQ WHERE FMI_0 = 3 AND FMINUM_0 = ' ')

SELECT * FROM SORDERQ WHERE FMI_0 = 3 AND FMINUM_0 = ' ' 

SELECT SOHNUM_0 AS A,SOPLIN_0 AS B,CREUSR_0,CREDAT_0,* FROM PORDERQ WHERE SOHNUM_0 = '0101SOH17020143' ORDER BY SOHNUM_0,SOPLIN_0
SELECT * FROM SORDERQ WHERE SOHNUM_0 IN
(SELECT SOHNUM_0 FROM 
(SELECT SOHNUM_0,SOPLIN_0 FROM 
(SELECT SOHNUM_0,SOPLIN_0,COUNT(SOHNUM_0) AS QTY_0 FROM PORDERQ GROUP BY SOHNUM_0,SOPLIN_0) A
WHERE A.QTY_0 <> 1) B)
SELECT POHNUM_0 FROM PORDERQ WHERE SOHNUM_0 = '0101SOH17020143' GROUP BY POHNUM_0

SELECT * FROM SORDERQ WHERE SOHNUM_0 = '0101SOH17020143'

SELECT * FROM SORDERQ WHERE POHNUM_0 = '0101POH17020917'

SELECT CONVERT()


SELECT * FROM MFGMAT
SELECT * FROM MFGHEAD
SELECT * FROM MFGITM
SELECT * FROM YMFGRQD
SELECT * FROM XMFGRQD





SELECT * FROM XMFGRQD
SELECT * FROM YMFGRQD