SELECT ITMREF_0 N'产品编码',
		STA_0 N'状态',
		SUM(QTYPCU_0) N'数量' 
FROM STOCK 
WHERE STOFCY_0 = N'0101' 
	AND LOC_0 = N'MI1'
GROUP BY ITMREF_0,STA_0
SELECT * FROM AUTILIS ORDER BY USR_0

SELECT SOHNUM_0 N'订单号',
		SOPLIN_0 N'订单行',
		BPCORD_0 N'客户编码',
		ITMREF_0 N'产品编码',
		QTY_0 N'订单数量',
		DLVQTY_0 N'已发货数量',
		INVQTY_0 N'已开票数量',
		DEMDLVDAT_0  N'要求发货日期'
FROM SORDERQ 
WHERE CREUSR_0 IN(N'0078',N'0031') 
		AND SOQSTA_0 < 3 
		AND SALFCY_0 = N'0101'
		AND QTY_0 <> DLVQTY_0
ORDER BY SOHNUM_0,SOPLIN_0

SELECT * FROM SINVOICED ORDER BY CREDAT_0

