SELECT B.ZPOATIPRI_0 内部采购价,
		C.SOHNUM_0,
		E.BPRNAM_0,
		A.BPCNAM_0,
		C.ITMREF_0,
		C.GROPRI_0 销售价,
		D.CHGRAT_0,
		B.ZPOATIPRI_0-C.GROPRI_0 差异,
		A.DLVQTY_0 ,
		A.QTY_0 ,
		A.INVQTY_0 
FROM ZSOYN A
	LEFT  JOIN PORDERP B ON A.POHNUM_0=B.POHNUM_0 AND A.POPLIN_0=B.POPLIN_0
	LEFT  JOIN SORDERP C ON A.SOHNUM_0=C.SOHNUM_0 AND A.SOPLIN_0=C.SOPLIN_0
	LEFT JOIN SORDER D ON A.SOHNUM_0=D.SOHNUM_0
	LEFT JOIN PORDER E ON A.POHNUM_0=E.POHNUM_0
WHERE ROUND(B.ZPOATIPRI_0,2) <> ROUND(C.GROPRI_0,2)




SELECT * FROM MFGMAT WHERE MFGNUM_0 = '0203MFG17070793'

SELECT * FROM 

SELECT * FROM AUTILIS WHERE USR_0 = 'LUCY'