SELECT T7.BPCORD_0 N'客户编码',
		T6.BPCNAM_0 N'客户名称',
		T7.AMOUNT N'销售金额'
FROM 
	(
		SELECT T9.BPCORD_0,
				SUM(T9.AMOUNT) AMOUNT	
		FROM 
			(
				SELECT T2.BPCORD_0,
						T1.GROPRI_0 * T2.QTY_0 AS AMOUNT
				FROM SORDERP T1
					LEFT JOIN SORDERQ T2 ON T1.SOHNUM_0 = T2.SOHNUM_0 AND T1.SOPLIN_0 = T2.SOPLIN_0 
				WHERE T1.SALFCY_0 = '0101'
				) T9
		GROUP BY T9.BPCORD_0
		) T7
	LEFT JOIN BPCUSTOMER T6 ON T7.BPCORD_0 = T6.BPCNUM_0
WHERE T7.BPCORD_0 = 'CHN-SH-4146'