SELECT * FROM ITMBPS WHERE ITMREF_0 = 'IIH5052'
SELECT * FROM ITMBPS WHERE BPSNUM_0 = 'CHN-SH-8334'

-- DELETE FROM ITMBPS WHERE BPSNUM_0 = 'CHN-SH-8334'

SELECT T1.MFGNUM_0,
		T1.MFGLIN_0,
		T1.ITMREF_0,
		T1.MFGSTA_0,
		T1.RETQTY_0,
		T1.STU_0,
		T1.STDQTY_0,
		T1.USEQTY_0,
		T1.ALLQTY_0,
		T1.SHTQTY_0,
		T1.YREQQTY_0
FROM MFGMAT T1
WHERE PLNFCY_0 = '0202'
	AND SHTQTY_0 > 0

SELECT * FROM MFGITM
SELECT * FROM MFGMAT
SELECT T1.MFGNUM_0 AS N'工单号',
		T2.ITMREF_0 AS N'产品',
		T1.ITMREF_0 AS N'组件',
		T1.STU_0 AS N'单位',
		T1.RETQTY_0 AS N'需求数量',
		T1.YREQQTY_0 AS N'已申领数量',
		T1.SHTQTY_0 AS N'短缺数量' 
FROM MFGMAT T1
	LEFT JOIN MFGITM T2 ON T1.MFGNUM_0 = T2.MFGNUM_0 AND T2.MFGLIN_0 = 1000
WHERE T1.PLNFCY_0 = '0202'
	AND T1.MFGNUM_0 IN (SELECT DISTINCT MFGNUM_0 
						FROM MFGITM 
						WHERE MFGFCY_0 = '0202' 
							AND CPLQTY_0 >= EXTQTY_0)
	AND T1.SHTQTY_0 > 0

SELECT * FROM SDELIVERYD
SELECT * FROM SDELIVERY
SELECT T1.SDHNUM_0 AS N'发货单号',
		T1.SOHNUM_0 AS N'销售订单号',
		T3.BPCNAM_0 AS N'客户名称',
		T1.ITMREF_0 AS N'产品名称',
		T1.QTY_0 AS N'产品数量',
		T1.GROPRI_0 AS N'产品单价',
		(T1.QTY_0 * T1.GROPRI_0 * CHGRAT_0) AS N'换算汇率后的金额',
		T2.CUR_0 AS N'币种',
		T2.CHGRAT_0 AS N'汇率',
		T1.CREUSR_0 AS N'制单人',
		T1.REP1_0 AS N'业务代表',
		(CASE T2.CFMFLG_0 WHEN 1 THEN N'否' WHEN 2 THEN N'是' END) AS N'审核标志',
		T1.CREDAT_0 AS N'制单日期'
FROM SDELIVERYD T1
	LEFT JOIN SDELIVERY	T2 ON T1.SDHNUM_0 = T2.SDHNUM_0
	LEFT JOIN BPCUSTOMER T3 ON T1.BPCORD_0 = T3.BPCNUM_0
WHERE T1.STOFCY_0 = '0101'

SELECT TOP 100 * FROM SRETURND
SELECT TOP 100 * FROM SORDERQ
SELECT TOP 100 * FROM SORDER
SELECT TOP 100 * FROM SORDERP

 SELECT SRETURN.UPDDAT_0, 
		SRETURN.SRHNUM_0, 
		SRETURND.ITMREF_0, 
		SRETURND.ITMDES1_0, 
		SRETURND.QTY_0, 
		SRETURND.STU_0, 
		SORDERQ.ZCUSNUM_0, 
		SORDERQ.SOHNUM_0, 
		SORDERQ.ZRMK_0, 
		SORDER.ZREMARK_0, 
		SRETURND.STOFCY_0
 FROM   ((x3v71sql.INNOTEC.SRETURN SRETURN 
		LEFT JOIN x3v71sql.INNOTEC.SRETURND SRETURND ON (SRETURN.SRHNUM_0=SRETURND.SRHNUM_0) AND (SRETURN.SDHNUM_0=SRETURND.SDHNUM_0)) 
		LEFT JOIN x3v71sql.INNOTEC.SORDERQ SORDERQ ON ((SRETURND.SDHNUM_0=SORDERQ.SDHNUM_0) AND (SRETURND.SDDLIN_0=SORDERQ.SDDLIN_0)) AND (SRETURND.ITMREF_0=SORDERQ.ITMREF_0)) 
		LEFT JOIN x3v71sql.INNOTEC.SORDER SORDER ON SORDERQ.SOHNUM_0=SORDER.SOHNUM_0
 WHERE  SRETURND.STOFCY_0=N'0101'
 ORDER BY SRETURN.SRHNUM_0

 SELECT TOP 100 * FROM SORDER
 SELECT TOP 100 * FROM CONTACTCRM

 SELECT CNTNUM_0,COUNT(CNTNUM_0) FROM CONTACTCRM GROUP BY CNTNUM_0

 SELECT * FROM PRETURN
 SELECT * FROM PRETURND
 SELECT * FROM PORDERQ
 SELECT * FROM PORDER
 SELECT * FROM PRECEIPT
 SELECT * FROM BPSUPPLIER
 SELECT * FROM CONTACTCRM

 SELECT CNTNUM_0,COUNT(CNTNUM_0) FROM CONTACTCRM WHERE LEFT(CNTNUM_0,1) = 'S'GROUP BY CNTNUM_0


 SELECT * FROM STOJOU WHERE LOT_0 = 'LO170202010872' AND VCRNUM_0 = '02011702QUA00000872'

 SELECT * FROM 




















