--SELECT * FROM AUTILIS  WHERE PRFFCT_0 = 'ADPLA'
--SELECT * FROM ATEXTE
--SELECT * FROM AFCTPRF
--SELECT * FROM AFONCTION WHERE MENU_0 = 'MDBOM' ORDER BY CODEXT_0

SELECT * 
FROM AFCTPRF T1
	LEFT JOIN AFONCTION T2 ON T1.FNC_0 = T2.CODINT_0
WHERE T1.PRFCOD_0 = 'YSALA' AND T2.MENU_0 = 'MCQU'


--DECLARE @P1 NVARCHAR(100)
--DECLARE @P2 NVARCHAR(100)
--SET @P1 = 'YSALA'
--SET @P2 = 'MRPRQS'
--DELETE FROM AFCTPRF WHERE PRFCOD_0 = @P1 AND FNC_0 IN(SELECT CODINT_0 FROM AFONCTION WHERE MENU_0 = @P2 )

--SELECT T1.CODEXT_0,
--		T2.TEXTE_0
--FROM AFONCTION T1
--	FULL JOIN ATEXTE T2 ON T1.CODINT_0 = T2.NOMOBJ_0
--WHERE T1.MENU_0 = 'PASTA'


--SELECT T1.PRFCOD_0,
--		T1.FNC_0,
--		T2.CLEREC_0,
--		T2.TEXTE_0
--FROM AFCTPRF T1
--	LEFT JOIN ATEXTE T2 ON T1.FNC_0 = T2.NOMOBJ_0
--	LEFT JOIN AFONCTION T3 ON T1.FNC_0 = T3.CODINT_0
--WHERE T1.PRFCOD_0 = 'YTIGA' AND T2.LAN_0 = 'CHI' AND T3.MENU_0 = 'PASTA'
--ORDER BY T1.FNC_0


--DELETE FROM AFCTPRF WHERE PRFCOD_0 = 'YMIGA'
--UPDATE AUTILIS SET PRFFCT_0 = 'ADMIN' WHERE PRFFCT_0 = 'YMIGA'


