SELECT A.POHNUM_0,
		A.POPLIN_0,
		B.SOHNUM_0,
		B.SOPLIN_0,
		C.SOHNUM_0,
		C.SOPLIN_0,
		B.BPCORD_0,
		D.BPCNAM_0,
		B.ITMREF_0,
		E.ITMDES1_0,
		C.QTYSTU_0,
		C.DLVQTY_0,
		B.ZCUSNUM_0,
		B.ZRMK_0,
		C.DEMDLVDAT_0,
		C.CREDAT_0,
		(CASE F.REOCOD_0 WHEN 1 THEN N'无提议' WHEN 2 THEN N'采购' WHEN 3 THEN N'生产' WHEN 4 THEN N'地点' WHEN 5 THEN N'外协'END) N'产品属性'
FROM PORDERQ A,SORDERQ B,SORDERQ C,BPCUSTOMER D,ITMMASTER E,ITMFACILIT F
WHERE (A.SOHNUM_0 = B.SOHNUM_0 AND A.SOPLIN_0 = B.SOPLIN_0) 
AND (C.POHNUM_0 = A.POHNUM_0 AND C.POPLIN_0 = A.POPLIN_0)
AND (D.BPCNUM_0 = B.BPCORD_0 AND B.ITMREF_0 = E.ITMREF_0)
AND (C.SALFCY_0 = F.STOFCY_0 AND C.ITMREF_0 = F.ITMREF_0)

SELECT * FROM ITMFACILIT
SELECT * FROM SORDERQ

SELECT * FROM STOJOU WHERE ITMREF_0 = 'IHJ0681' AND STOFCY_0 = '0202'

SELECT * FROM SDELIVERYD WHERE SDHNUM_0 = '0201SDI17040200'

