--SELECT * FROM SDELIVERY
--SELECT * FROM SORDER

SELECT T1.CREDAT_0 N'订单日期',
		T1.SOHNUM_0 N'销售订单号',
		T2.BPCNAM_0 N'客户名称',
		T1.ITMREF_0 N'产品编码',
		T3.ITMDES1_0 N'产品名称',
		T1.ZCUSNUM_0 N'客户订单号',
		T4.SDHNUM_0 N'发货单号',
		T4.QTY_0 N'发货数量',
		T4.CREDAT_0 N'发货日期',
		T5.CFMFLG_0 N'发货状态',
		T6.QTY_0 N'发票数量',
		T7.GROPRI_0 N'无税单价',
		T2.CUR_0 N'币种',
		T7.GROPRI_0 * T1.QTY_0 N'原币未税金额',
		(CASE WHEN T2.CUR_0  = N'CNY' THEN T7.GROPRI_0 * T1.QTY_0 ELSE T7.GROPRI_0 * T1.QTY_0 * T2.CHGRAT_0 END) N'外币未税金额',
		T2.CHGRAT_0 N'汇率',
		T8.BPRNAM_0 N'销售代表',
		T9.NOMUSR_0 N'销售订单创建用户'
FROM SORDERQ T1
	LEFT JOIN SORDER T2 ON T1.SOHNUM_0 = T2.SOHNUM_0
	LEFT JOIN ITMMASTER T3 ON T1.ITMREF_0 = T3.ITMREF_0
	LEFT JOIN SDELIVERYD T4 ON T1.SDHNUM_0 = T4.SDHNUM_0 AND T1.SDDLIN_0 = T4.SDDLIN_0
	LEFT JOIN SDELIVERY T5 ON T1.SDHNUM_0 = T5.SDHNUM_0
	LEFT JOIN SINVOICED T6 ON T4.SDHNUM_0 = T6.SDHNUM_0 AND T4.SDDLIN_0 = T6.SDDLIN_0
	LEFT JOIN SORDERP T7 ON T1.SOHNUM_0 = T7.SOHNUM_0 AND T1.SOPLIN_0 = T7.SOPLIN_0
	LEFT JOIN BPARTNER T8 ON T2.REP_0 = T8.BPRNUM_0
	LEFT JOIN AUTILIS T9 ON T1.CREUSR_0 = T9.USR_0
WHERE T1.SALFCY_0 = '0101'
	

