SELECT  T1.SOHNUM_0 N'销售单号',
		T1.BPCORD_0 N'客户编码',
		T2.BPCNAM_0 N'客户名称',
		T1.ITMREF_0 N'产品代码',
		T3.ITMDES1_0 N'产品名称',
		T1.QTY_0 N'数量',
		T1.DLVQTY_0 N'已发数量',
		T1.QTY_0 - T1.DLVQTY_0 N'待发数量',
		T1.DEMDLVDAT_0 N'要求发货日期',
		LEFT(T4.XSOHNUM_0,4) N'所属事业部'
FROM SORDERQ T1  
	LEFT JOIN BPCUSTOMER T2 ON T1.BPCORD_0 = T2.BPCNUM_0 
	LEFT JOIN ITMMASTER T3 ON T1.ITMREF_0 = T3.ITMREF_0 
	LEFT JOIN ZSOYN T4 ON T1.SOHNUM_0 = T4.SOHNUM_0 AND T1.SOPLIN_0 = T4.SOPLIN_0
	LEFT JOIN SORDER T5 ON T1.SOHNUM_0 = T5.SOHNUM_0
WHERE T5.ORDSTA_0 <> 2 AND (T1.BPCORD_0 IN(N'CHN-JS-4867') OR T1.SOHNUM_0 IN(SELECT SOHNUM_0 FROM SORDERQ WHERE ITMREF_0 LIKE N'M%' AND QTY_0 - DLVQTY_0 > 0 GROUP BY SOHNUM_0))
ORDER BY T1.SOHNUM_0


SELECT A.SOHNUM_0 FROM SORDERQ A LEFT JOIN SORDER B ON A.SOHNUM_0 = B.SOHNUM_0 WHERE A.ITMREF_0 LIKE N'M%' AND B.ORDSTA_0 <> 2 GROUP BY A.SOHNUM_0 ORDER BY A.SOHNUM_0
SELECT SOHNUM_0 FROM SORDERQ WHERE ITMREF_0 LIKE N'M%' GROUP BY SOHNUM_0


SELECT * FROM BPCUSTOMER