SELECT T1.STOFCY_0 N'事业部',
		T1.ITMREF_0 N'物料代码',
		T6.ITMDES1_0 N'物料名称',
		T5.LANMES_0 N'物料属性',
		T6.STU_0 N'单位',
		ISNULL(T2.QTYSTU_0,0) N'库存数量',
		ISNULL(T3.QTYSTU_0,0) N'预计入库量',
		ISNULL(T4.QTY_0,0) N'订单分配量',
		ISNULL(T7.QTY_0,0) N'工单分配量'
FROM ITMFACILIT T1
	LEFT JOIN (SELECT STOFCY_0,ITMREF_0,SUM(QTYSTU_0) QTYSTU_0 FROM STOCK WHERE STA_0 IN( 'A','Q') GROUP BY STOFCY_0,ITMREF_0) T2 ON T1.ITMREF_0 = T2.ITMREF_0 AND T1.STOFCY_0 = T2.STOFCY_0
	LEFT JOIN (SELECT POHFCY_0,ITMREF_0,SUM(QTYSTU_0 - RCPQTYPUU_0) QTYSTU_0 FROM PORDERQ WHERE LINSTA_0 <> 3 AND LINCLEFLG_0 = 1 GROUP BY POHFCY_0,ITMREF_0) T3 ON T1.ITMREF_0 = T3.ITMREF_0 AND T1.STOFCY_0 = T3.POHFCY_0
	LEFT JOIN (SELECT SALFCY_0,ITMREF_0,(SUM(QTY_0)-SUM(DLVQTY_0)) QTY_0 FROM SORDERQ WHERE SOQSTA_0 <> 3 AND DEMSTA_0 <> 4 GROUP BY SALFCY_0,ITMREF_0 ) T4 ON T1.ITMREF_0 = T4.ITMREF_0 AND T1.STOFCY_0 = T4.SALFCY_0
	LEFT JOIN APLSTD T5 ON T1.REOCOD_0 = T5.LANNUM_0 AND T5.LANCHP_0 = '250' AND T5.LAN_0 = 'CHI'
	LEFT JOIN ITMMASTER T6 ON T1.ITMREF_0 = T6.ITMREF_0
	LEFT JOIN (SELECT T1.MFGFCY_0,T1.ITMREF_0,SUM(T1.RETQTY_0 - T1.USEQTY_0) QTY_0 FROM MFGMAT T1	LEFT JOIN MFGHEAD T2 ON T1.MFGNUM_0 = T2.MFGNUM_0 WHERE T2.MFGSTA_0 <> '4' GROUP BY T1.MFGFCY_0,T1.ITMREF_0 ) T7 ON T1.ITMREF_0 = T7.ITMREF_0 AND T1.STOFCY_0 = T7.MFGFCY_0
WHERE T2.QTYSTU_0 IS NOT NULL
	OR T3.QTYSTU_0 IS NOT NULL
	OR T4.QTY_0 IS NOT NULL
	OR T7.QTY_0 IS NOT NULL
ORDER BY T1.STOFCY_0,T1.ITMREF_0