SELECT B.FCY_0,
		B.NUM_0,
		B.BPR_0,
		B.BPRNAM_0,
		B.SIVTYP_0,
		B.CUR_0,
		B.RATMLT_0,
		A.SIDLIN_0,
		D.LANMES_0,
		A.ITMREF_0,
		A.ITMDES_0,
		A.QTYSTU_0,
		A.NETPRI_0*B.RATMLT_0 含税价RMB,
		A.NETPRINOT_0*B.RATMLT_0 不含税价RMB,
		B.RATMLT_0 汇率,
		C.PRIVAL_0 成本价,
		AMTATILIN_0*B.RATMLT_0,
		AMTNOTLIN_0*B.RATMLT_0,
		A.AMTTAXLIN_0*B.RATMLT_0,
		E.BPCNAM_0,
		E.SOHNUM_0
FROM SINVOICED A
	INNER JOIN  SINVOICE B ON A.NUM_0=B.NUM_0
	LEFT JOIN (SELECT DISTINCT VCRNUM_0,VCRLIN_0,PRIVAL_0 FROM STOJOU ) C ON  A.SDHNUM_0= C.VCRNUM_0 AND A.SDDLIN_0=C.VCRLIN_0
	INNER JOIN (SELECT A.STOFCY_0,A.ITMREF_0,A.REOCOD_0,B.LANMES_0 FROM ITMFACILIT A
	LEFT JOIN  APLSTD B ON A.REOCOD_0=B.LANNUM_0 AND  B.LANCHP_0=250 AND B.LAN_0='CHI') D ON D.STOFCY_0=B.FCY_0 AND D.ITMREF_0=A.ITMREF_0
	LEFT JOIN ZSOYN E ON A.SOHNUM_0 = E.XSOHNUM_0 AND A.SOPLIN_0 = E.XSOPLIN_0
WHERE B.ACCDAT_0 BETWEEN '2017-10-01' AND '2017-10-31'
		AND FCY_0 IN ('0201','0202','0203')

SELECT TOP 100 * FROM SINVOICED WHERE CPY_0 = '02'