 SELECT "MFGMATTRK"."USEQTY_0", 
		"MFGMAT"."MFGNUM_0",
		"MFGMAT"."BOMSEQ_0", 
		"ZMMT"."MFGTRKNUM_0", 
		"MFGITM"."EXTQTY_0", 
		"MFGITM"."ITMREF_0", 
		"ZMMT"."MFGNUM_0", 
		"ZMMT"."MFGFCY_0", 
		"ITMMASTER"."ITMREF_0", 
		"ITMMASTER"."ITMDES1_0", 
		"MFGMATTRK"."STU_0", 
		"MFGMAT"."USEQTY_0", 
		"MFGMAT"."RETQTY_0", 
		"ZSOYN"."SOHNUM_0", 
		"ZSOYN"."XSOHNUM_0", 
		"ZSOYN"."BPCORD_0", 
		"ZSOYN"."BPCNAM_0", 
		"ZSOYN"."ZRMK_0", 
		"MFGMATTRK"."IPTDAT_0", 
		"MFGITM"."MFGLIN_0"
 FROM   (
			(
				(
				("x3"."INNO"."ZMMT" "ZMMT" 
					LEFT OUTER JOIN "x3"."INNO"."MFGMAT" "MFGMAT" ON "ZMMT"."MFGNUM_0"="MFGMAT"."MFGNUM_0") 
					LEFT OUTER JOIN "x3"."INNO"."MFGITM" "MFGITM" ON "ZMMT"."MFGNUM_0"="MFGITM"."MFGNUM_0") 
					LEFT OUTER JOIN "x3"."INNO"."MFGMATTRK" "MFGMATTRK" ON (("MFGMAT"."MFGNUM_0"="MFGMATTRK"."MFGNUM_0") AND ("MFGMAT"."MFGLIN_0"="MFGMATTRK"."MFGLIN_0")) AND ("MFGMAT"."BOMSEQ_0"="MFGMATTRK"."BOMSEQ_0")) 
					LEFT OUTER JOIN "x3"."INNO"."ITMMASTER" "ITMMASTER" ON "MFGMAT"."ITMREF_0"="ITMMASTER"."ITMREF_0") 
					LEFT OUTER JOIN "x3"."INNO"."ZSOYN" "ZSOYN" ON ("MFGITM"."VCRNUMORI_0"="ZSOYN"."SOHNUM_0") AND ("MFGITM"."VCRLINORI_0"="ZSOYN"."SOPLIN_0")
 WHERE  "ZMMT"."MFGTRKNUM_0"=N'0201MTK17060328' 
	AND ("MFGMATTRK"."IPTDAT_0">={ts '2017-02-01 00:00:00'} 
	AND "MFGMATTRK"."IPTDAT_0"<{ts '2017-07-01 00:00:00'}) 
	AND "ZMMT"."MFGFCY_0"=N'0201' AND "MFGITM"."MFGLIN_0"=1000
 ORDER BY "ZMMT"."MFGTRKNUM_0", "MFGMAT"."MFGNUM_0", "MFGMAT"."BOMSEQ_0"


 SELECT * FROM ZMMT
 sp_helptext ZMMT

 SELECT MFGTRKNUM_0,MFGNUM_0,MFGFCY_0,IPTDAT_0,CREDAT_0,CREUSR_0 FROM MFGMATTRK GROUP BY MFGTRKNUM_0,MFGNUM_0,MFGFCY_0,IPTDAT_0,CREDAT_0,CREUSR_0

 SELECT * FROM MFGMAT WHERE MFGNUM_0 = '0201MFG17051113'
 SELECT * FROM MFGMATTRK T1
	LEFT JOIN MFGMAT T2 ON T1.MFGNUM_0 = T2.MFGNUM_0 AND T1.BOMSEQ_0 = T2.BOMSEQ_0 AND T1.MFGLIN_0 = T2.MFGLIN_0
  WHERE T1.MFGTRKNUM_0 = '0201MTK17060328'
	AND T2.STA_0 <> 4
