

SELECT *
FROM (SELECT PRFCOD_0,FNC_0 FROM AFCTPRF WHERE PRFCOD_0 = 'YMIGA') T1
	FULL JOIN (SELECT PRFCOD_0,FNC_0 FROM AFCTPRF WHERE PRFCOD_0 = 'YSTOA') T2 ON T1.FNC_0 = T2.FNC_0
WHERE T1.PRFCOD_0 IS NULL OR T2.PRFCOD_0 IS NULL



SELECT * FROM AFONCTION
SELECT * FROM ATEXTE

SELECT T1.CODINT_0,
		T2.TEXTE_0
FROM AFONCTION T1
	LEFT JOIN ATEXTE T2 ON T1.CODINT_0 = T2.NOMOBJ_0
WHERE T2.LAN_0 = 'CHI'
ORDER BY T1.CODINT_0