CREATE TRIGGER UPDATEDELIVERQTY
ON SORDERQ
FOR UPDATE
AS 
BEGIN   

IF UPDATE(DLVQTY_0) 
	UPDATE T2
	SET T2.LFTQTY_0 =  T1.DLVQTY_0
	FROM INSERTED T1 ,ZTSDELIVERYD T2 
	WHERE SORDERQ.SOHNUM_0 = ZTSDELIVERYD.SOHNUM_0 
		AND SORDERQ.ITMREF_0 = ZTSDELIVERYD.ITMREF_0 

END


SELECT * FROM SORDERQ WHERE ITMREF_0 = 'MVB0001'