 SELECT "XMFGRQD"."VCRNUM_0", 
		"XMFGRQD"."OVCRNUM_0",
		"XMFGRQD"."LOC_0", 
		"XMFGRQD"."LOCDES_0", 
		"XMFGRQD"."ITMREF_0", 
		"XMFGRQD"."ITMDES1_0", 
		"XMFGRQD"."STU_0", 
		"XMFGRQD"."QTYSTU_0",
		"MFGITM"."ITMREF_0", 
		"MFGITM"."EXTQTY_0", 
		"FACILITY"."FCYNAM_0",
		"YMFGRQH"."ORDNUM_0",
		"XMFGRQH"."CREDAT_0"
 FROM   {oj ((("x3v71sql"."INNOTEC"."XMFGRQD" "XMFGRQD" 
	LEFT OUTER JOIN "x3v71sql"."INNOTEC"."XMFGRQH" "XMFGRQH" ON "XMFGRQD"."VCRNUM_0"="XMFGRQH"."VCRNUM_0") 
	INNER JOIN "x3v71sql"."INNOTEC"."YMFGRQH" "YMFGRQH" ON "XMFGRQD"."OVCRNUM_0"="YMFGRQH"."VCRNUM_0") 
	INNER JOIN "x3v71sql"."INNOTEC"."MFGITM" "MFGITM" ON "YMFGRQH"."ORDNUM_0"="MFGITM"."MFGNUM_0") 
	LEFT OUTER JOIN "x3v71sql"."INNOTEC"."FACILITY" "FACILITY" ON "XMFGRQH"."STOFCY_0"="FACILITY"."FCY_0"}
 WHERE  "XMFGRQD"."VCRNUM_0"='MRS020217010002' AND ("XMFGRQH"."CREDAT_0">={ts '2017-01-01 00:00:00'} AND "XMFGRQH"."CREDAT_0"<{ts '2017-03-24 00:00:00'})
 ORDER BY "XMFGRQD"."VCRNUM_0", "XMFGRQD"."OVCRNUM_0"
