SELECT ITMREF_0 FROM ITMFACILIT WHERE ITMREF_0 = N'' AND STOFCY_0 = '0201'


SELECT * FROM AOBJEXTD WHERE EXT_0 = 'ZROU'

SELECT * FROM ITMFACILIT WHERE ITMREF_0 LIKE N'T%' ORDER BY ITMREF_0


SELECT ITMREF_0 FROM BOM WHERE ITMREF_0 = 'ICN0001' AND BOMALTTYP_0 = 3


SELECT * FROM MFGHEAD WHERE MFGFCY_0 = '0201' AND CREUSR_0 NOT IN (N'0006',N'0084') AND CREDAT_0 BETWEEN N'2017-07-01' AND GETDATE()

SELECT * FROM AUTILIS



SELECT T1.ITMREF_0 N'产品代码',T2.ITMDES1_0 N'产品名称',T2.STU_0 N'单位',T1.STOFCY_0 N'事业部' FROM ITMFACILIT T1 LEFT JOIN ITMMASTER T2 ON T1.ITMREF_0 = T2.ITMREF_0
SELECT MFGFCY_0,SUM(RETQTY_0) FROM MFGMAT WHERE ITMREF_0 = 'IHQ0508-01' GROUP BY MFGFCY_0