
SELECT TOP 100 * FROM MFGITM
SELECT TOP 100 * FROM PORDERQ
SELECT TOP 100 * FROM MFGMAT
SELECT ITMREF_0,PRHFCY_0,SUM(QTYSTU_0 - RCPQTYSTU_0) FROM PORDERQ WHERE LINCLEFLG_0 = 1 GROUP BY ITMREF_0,PRHFCY_0

SELECT ITMREF_0,SALFCY_0,SUM(QTY_0 - DLVQTY_0) QTY_0 FROM SORDERQ WHERE DEMSTA_0 <> 4 GROUP BY ITMREF_0,SALFCY_0
SELECT ITMREF_0,MFGFCY_0,SUM(RETQTY_0 - USEQTY_0) QTY_0 FROM MFGMAT WHERE MFGSTA_0 <> 4 GROUP BY ITMREF_0,MFGFCY_0

SELECT REOCOD_0,* FROM ITMFACILIT WHERE ITMREF_0 = N'IFT0151' AND STOFCY_0 = N'0201'

UPDATE ITMFACILIT SET REOCOD_0 = 2 WHERE ITMREF_0 = N'' AND STOFCY_0 = N'0201' AND REOCOD_0 = 4
 