SELECT T1.ITMREF_0 N'产品编码',
		T2.ITMDES1_0 N'产品名称',
		T3.QTYSTU_0 N'A状态库存',
		T4.QTY_0 N'销售订单需求',
		T5.RETQTY_0 N'工单需求',
		T6.QTYSTU_0 N'采购订单在途'
FROM ITMFACILIT T1
	LEFT JOIN ITMMASTER T2 ON T1.ITMREF_0 = T2.ITMREF_0
	LEFT JOIN (SELECT  STOFCY_0,
						ITMREF_0,
						SUM(QTYSTU_0) QTYSTU_0
				FROM STOCK 
				WHERE STA_0 = N'A'
				GROUP BY ITMREF_0,STOFCY_0
				) T3 
				ON T1.ITMREF_0 = T3.ITMREF_0 AND T1.STOFCY_0 = T3.STOFCY_0
	LEFT JOIN (SELECT STOFCY_0,
						ITMREF_0,
						SUM(QTY_0) QTY_0 
			   FROM SORDERQ 
			   WHERE SOQSTA_0 < 3 
			   GROUP BY STOFCY_0,ITMREF_0
			   ) T4 
			   ON T1.STOFCY_0 = T4.STOFCY_0 AND T1.ITMREF_0 = T4.ITMREF_0
	LEFT JOIN (SELECT MFGFCY_0,
						ITMREF_0,
						SUM(RETQTY_0) RETQTY_0 
				FROM MFGMAT 
				WHERE RETQTY_0 - USEQTY_0 > 0 AND MATSTA_0 < 3 
				GROUP BY MFGFCY_0,ITMREF_0
				) T5 
				ON T1.STOFCY_0 = T5.MFGFCY_0 AND T1.ITMREF_0 = T5.ITMREF_0
	LEFT JOIN (SELECT POHFCY_0,
						ITMREF_0,
						SUM(QTYSTU_0) QTYSTU_0 
				FROM PORDERQ 
				WHERE QTYSTU_0 - RCPQTYSTU_0 > 0 AND LINCLEFLG_0 =1
				GROUP BY POHFCY_0,ITMREF_0
				) T6 
				ON T1.STOFCY_0 = T6.POHFCY_0 AND T1.ITMREF_0 = T6.ITMREF_0
WHERE T1.STOFCY_0 = N'0201'

