--SELECT * FROM APLSTD WHERE LAN_0 = N'CHI' AND LANMES_0 = N'成本管理控制'

--SELECT * FROM AFONCTION WHERE MENU_0 = N'MDBA'


--SELECT TOP 100 * FROM ATEXTE WHERE NUMERO_0 = N'11192'


--SELECT ID
--		T1.MENU_0,
--		T1.CODEXT_0,
--		T2.TEXTE_0
--FROM AFONCTION T1
--	LEFT JOIN ATEXTE T2 ON T1.NOM_0 = T2.NUMERO_0 AND LAN_0 = N'CHI'
--WHERE T1.MENU_0 = N'GENE'

--SELECT * FROM AUTILIS
--SELECT USR_0,NOMUSR_0,PRFFCT_0 FROM AUTILIS WHERE ENAFLG_0 = N'2' ORDER BY USR_0
--SELECT PRFCOD_0 FROM AFCTPRF GROUP BY PRFCOD_0 


--WITH FUNC AS
--(
--	SELECT MENU_0,
--			CODEXT_0,
--			NOM_0,
--			LEV = 1,
--			PX = CAST(ROW_NUMBER() OVER(ORDER BY RANG_0) AS varbinary)
--	FROM AFONCTION
--	WHERE AFONCTION.MENU_0 = N'GENE'
--	UNION ALL
--	SELECT A2.MENU_0,
--			A2.CODEXT_0,
--			A2.NOM_0,
--			LEV + 1,
--			CAST(PX + CAST(ROW_NUMBER() OVER(ORDER BY A2.RANG_0) AS varbinary) AS varbinary)
--	FROM AFONCTION A2
--	JOIN  FUNC A1 ON A2.MENU_0 = A1.CODEXT_0
--)
--SELECT T1.MENU_0,
--		T1.CODEXT_0,
--		T2.TEXTE_0,
--		LEV
--FROM FUNC T1
--	LEFT JOIN ATEXTE T2 ON T1.NOM_0 = T2.NUMERO_0 AND T2.LAN_0 = N'CHI'
--ORDER BY PX




SELECT TOP 100 * FROM AMSKZON WHERE CODMSK_0 = N'POH3' AND CODZON_0 = N'MDL'
SELECT TOP 100 * FROM ATEXTE WHERE NOMZON_0 = N'POH3' AND LAN_0 = N'CHI' AND NUMERO_0 = N'1722'
SELECT TOP 100 * FROM ATEXTE WHERE TEXTE_0 = N'供应商订单'
SELECT TOP 100 * FROM AMSK WHERE ABRMSK_0 = N'POH3'
SELECT TOP 100 * FROM ATEXTRA WHERE TEXTE_0 = N'屏幕字典'
SELECT TOP 100 * FROM ATEXTEXCEP

SELECT	T3.ABRMSK_0,
		T1.CODMSK_0,
		T4.TEXTE_0,
		T1.CODZON_0,
		T2.TEXTE_0
FROM AMSKZON T1
	LEFT JOIN ATEXTE T2 ON T1.CODZON_0 = T2.NOMZON_0 AND T1.INTIT_0 = T2.NUMERO_0 AND T2.LAN_0 = N'CHI'
	LEFT JOIN AMSK T3 ON T1.CODMSK_0 = T3.CODMSK_0
	LEFT JOIN ATEXTE T4 ON T3.INTMSK_0 = T4.NUMERO_0 AND T4.LAN_0 = N'CHI'
WHERE T1.SAIAFF_0 <> 3
	AND T2.TEXTE_0 IS NOT NULL
ORDER BY T3.ABRMSK_0

