SELECT T1.PRHFCY_0 N'事业部',
		T1.RCPDAT_0 N'收货日期',
		T1.POHNUM_0 N'采购订单号',
		T1.PTHNUM_0 N'收货单号',
		T1.BPSNUM_0 N'供应商编码',
		T3.BPSNAM_0 N'供应商名称',
		T1.ITMREF_0 N'产品代码',
		T2.ITMDES1_0 N'产品名称',
		T1.STU_0 N'单位',
		T1.QTYPUU_0 N'收货数量',
		T1.QTYPUU_0 * NETPRI_0  N'金额'
FROM PRECEIPTD T1
	LEFT JOIN ITMMASTER T2 ON T1.ITMREF_0 = T2.ITMREF_0
	LEFT JOIN BPSUPPLIER T3 ON T1.BPSNUM_0 = T3.BPSNUM_0


SELECT * FROM BPSUPPLIER

SELECT TOP 1000 * FROM PRECEIPTD