Select 'DROP VIEW ' + TABLE_SCHEMA + '.[' + TABLE_NAME+']' from INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA in ('SEED')
Select 'DROP TABLE ' + TABLE_SCHEMA + '.[' + TABLE_NAME+']' from INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA in ('SEED')
SELECT 'DROP SEQUENCE ' + TABLE_SCHEMA + '.[' + TABLE_SCHEMA + ']' FROM INFORMATION_SCHEMA.TABLES


Drop User SEED
Drop User SEED_REPORT
Drop Schema SEED

USE [INNOTEC]
GO
SELECT 'DROP SEQUENCE SEED.['+ name +']',name, object_id, type_desc
FROM sys.objects 
WHERE OBJECTPROPERTY(object_id, N'SchemaId') = SCHEMA_ID(N'SEED')
ORDER BY type_desc, name;
GO



SELECT * FROM sys.objects 