--SELECT * FROM MFGITM
--SELECT * FROM MFGMAT
--SELECT * FROM ITMCOST
--SELECT * FROM MFGITM
SELECT *
FROM	(
		SELECT ITMREF_0,
			   MFGFCY_0
		FROM MFGITM
		WHERE MFGSTA_0 <> '4'
		UNION
		SELECT ITMREF_0,
			   MFGFCY_0
		FROM MFGMAT
		WHERE MFGSTA_0 <> '4'
		) T1
WHERE T1.ITMREF_0 NOT IN(SELECT ITMREF_0 FROM ITMCOST)
ORDER BY MFGFCY_0
--SELECT GETDATE() +7