--SELECT * FROM MFGITM
--SELECT * FROM MFGMAT
SELECT T1.MFGNUM_0 AS N'工单号',
		T2.ITMREF_0 AS N'产品',
		T1.ITMREF_0 AS N'组件',
		T1.STU_0 AS N'单位',
		T1.RETQTY_0 AS N'需求数量',
		T1.YREQQTY_0 AS N'已申领数量',
		T1.SHTQTY_0 AS N'短缺数量' 
FROM MFGMAT T1
	LEFT JOIN MFGITM T2 ON T1.MFGNUM_0 = T2.MFGNUM_0 AND T2.MFGLIN_0 = 1000
WHERE T1.PLNFCY_0 = '0202'
	AND T1.MFGNUM_0 IN (SELECT DISTINCT MFGNUM_0 
						FROM MFGITM 
						WHERE MFGFCY_0 = '0202' 
							AND CPLQTY_0 >= EXTQTY_0)
	AND T1.SHTQTY_0 > 0