-- SELECT TOP 1000 * FROM MFGMAT
-- SELECT TOP 1000 * FROM MFGITM
-- SELECT TOP 1000 * FROM 





SELECT  T1.MFGNUM_0 N'工单号',
		T1.ITMREF_0 N'产品代码',
		T1.MFGFCY_0 N'事业部',
		T1.LIKQTY_0 N'单位用量',
		T1.STU_0 N'单位',
		T1.RETQTY_0 N'需求数量',
		T1.USEQTY_0 N'已消耗量',
		(T1.RETQTY_0 - T1.USEQTY_0) N'缺料量',
		T3.ITMDES1_0 N'产品名称',
		T4.ITMREF_0 N'成品代码',
		ISNULL(T5.SOHNUM_0,T6.SOHNUM_0) N'销售订单号',
		ISNULL(T5.BPCORD_0,T6.BPCORD_0) N'客户代码',
		ISNULL(T5.BPCNAM_0,T6.BPCNAM_0) N'客户名称',
		ISNULL(T5.XSOHNUM_0,T6.XSOHNUM_0) N'内部订单号'
FROM MFGMAT T1
	RIGHT JOIN (SELECT MFGNUM_0 FROM MFGMATTRK GROUP BY MFGNUM_0) T2 ON T1.MFGNUM_0 = T2.MFGNUM_0
	LEFT JOIN ITMMASTER T3 ON T1.ITMREF_0 = T3.ITMREF_0
	LEFT JOIN MFGITM T4 ON T1.MFGNUM_0 = T4.MFGNUM_0
							AND T4.MFGLIN_0 = 1000
	LEFT JOIN ZSOYN T5 ON T4.VCRNUMORI_0 = T5.SOHNUM_0
							AND T4.VCRLINORI_0 = T5.SOPLIN_0
	LEFT JOIN ZSOYN1 T6 ON T4.VCRNUMORI_0 = T6.XSOHNUM_0
							AND T4.VCRLINORI_0 = T6.XSOPLIN_0
WHERE T1.USEQTY_0 <> T1.RETQTY_0

