SELECT T1.PRFCOD_0,
		T1.FNC_0,
		T1.OPT_0,
		T2.CODACT_0,
		T2.CODINT_0,
		T2.MENU_0,
		T3.TEXTE_0
FROM AFCTPRF T1
	LEFT JOIN AFONCTION T2 ON T1.FNC_0 = T2.CODINT_0
	LEFT JOIN ATEXTE T3 ON T2.NOM_0 = T3.NUMERO_0 AND T3.LAN_0 = N'CHI'
WHERE T1.PRFCOD_0 = N'YSTOA'
	AND T3.TEXTE_0 LIKE N'%分配%'



SELECT * FROM AFCTPRF WHERE PRFCOD_0 LIKE N'YTECA%'
SELECT * INTO AFCTPRF FROM AFCTPRF WHERE PRFCOD_0 = N'YSTOB'

INSERT INTO AFCTPRF  SELECT * FROM AFCTPRF WHERE PRFCOD_0 = N'YSTOA'

SELECT * FROM AFCTPRF WHERE PRFCOD_0 = N'YSTOA' AND FNC_0 = N'CONSALLA'
UPDATE AFCTPRF SET FCYGRUCOD_0 = 1, FCYGRU_0 = N'' WHERE FCYGRUCOD_0 = 2 AND PRFCOD_0 = N'YSTOA'
DELETE FROM AFCTPRF WHERE PRFCOD_0 = N'YSTOB'

SELECT * FROM AUTILIS WHERE PRFFCT_0 = 'ADMIN' AND ENAFLG_0 = 2  ORDER BY USR_0
INSERT INTO AFCTPRF(PRFCOD_0,FNC_0,FCYGRUCOD_0,FCYGRU_0,ACS_0,OPT_0,CREDAT_0,CREUSR_0,UPDDAT_0,UPDUSR_0,CREDATTIM_0,UPDDATTIM_0,AUUID_0) VALUES()
sp_help AFCTPRF

INSERT INTO AFCTPRF(PRFCOD_0,FNC_0,FCYGRUCOD_0,FCYGRU_0,ACS_0,OPT_0,CREDAT_0,CREUSR_0,UPDDAT_0,UPDUSR_0,CREDATTIM_0,UPDDATTIM_0,AUUID_0) VALUES('YSTOB','GESYRI','2','0201','2','',GETDATE(),'ADMIN',GETDATE(),'ADMIN',GETDATE(),GETDATE(),NEWID())



SELECT  * FROM AMSKZON WHERE CODMSK_0 LIKE N'CONSCSF%'  AND CODZON_0 IN(N'NETPRINOT',N'CHGRAT',N'NETPRIATI',N'DEP',N'PFM',N'CPRPRI')
UPDATE AMSKZON SET CODACC_0 = 'ZXSJG' WHERE CODMSK_0 LIKE N'WMCSFSTD%'  AND CODZON_0 IN(N'NETPRINOT',N'CHGRAT',N'NETPRIATI',N'DEP',N'PFM',N'CPRPRI')

SELECT * FROM AMSKZON WHERE CODMSK_0 LIKE N'CONSCSF2%' AND CODACC_0 <> ''
SELECT * FROM AMSKZON WHERE CODACC_0 = 'ZXSJG'

SELECT  T1.CODACC_0,
		T1.CODMSK_0,
		T1.CODTYP_0,
		T1.CODZON_0,
		T2.TEXTE_0 
FROM AMSKZON T1
	LEFT JOIN ATEXTE T2 ON T1.CODZON_0 = T2.NOMOBJ_0 AND T2.LAN_0 = N'CHI'
WHERE T1.CODMSK_0 LIKE N'WK4ALL2%' 

SELECT * 
FROM AMSKZON T1
	LEFT JOIN ATEXTE T2 ON T1.CODZON_0 = T2.NOMOBJ_0 AND T2.LAN_0 = N'CHI'
WHERE T1.CODMSK_0

SELECT T1.CODINT_0,
		T2.TEXTE_0 
FROM AFONCTION T1
	LEFT JOIN ATEXTE T2 ON T1.NOM_0 = T2.NUMERO_0 AND T2.LAN_0 = N'CHI'
WHERE T2.TEXTE_0 LIKE N'%成本%'

SELECT * FROM AFONCTION
SELECT * FROM ATEXTE
SELECT TOP 1000 * FROM ATEXTRA WHERE TEXTE_0 = N'销售单位'
SELECT TOP 1000 * FROM ATEXTE WHERE TEXTE_0 = N'销售单位'

SELECT TOP 100 * FROM SORDERP


SELECT T1.CREDAT_0 AS N'制单日期',
    T3.ZCUSNUM_0 AS N'客户订单号',
    T3.ZCUSNUMLIN_0 AS N'客户订单行号',
    T1.SDHNUM_0 AS N'发货单号',
    T4.BPCNAM_0 AS N'客户名称',
    T1.SOHNUM_0 AS N'销售单号',
    T4.BPCORD_0 AS N'客户代码',
    T1.ITMREF_0 AS N'产品代码',
    T1.ITMDES1_0 AS N'产品名称',
    T1.STU_0 AS N'产品单位',
    T1.QTY_0 AS N'发货数量',
    T3.QTY_0 AS N'订单数量',
    T1.GROPRI_0 AS N'单价',
    (T1.QTY_0 * T1.GROPRI_0) AS N'金额',
    T3.ZRMK_0 AS N'备注',
    T4.ZREMARK_0 AS N'客户备注',
    (CASE T2.CFMFLG_0 WHEN 1 THEN N'已审核' WHEN 2 THEN N'未审核' END)  AS N'发货单状态',
	CAST(RIGHT(T5.VAT_0,2) AS FLOAT) / 100 N'税率'
FROM SDELIVERYD T1
  LEFT JOIN SDELIVERY T2 ON T1.SDHNUM_0 = T2.SDHNUM_0
  LEFT JOIN SORDERQ T3 ON T1.SOHNUM_0 = T3.SOHNUM_0 AND T1.SOPLIN_0 = T3.SOPLIN_0
  LEFT JOIN SORDER T4 ON T1.SOHNUM_0 = T4.SOHNUM_0
  LEFT JOIN SORDERP T5 ON T1.SOHNUM_0 = T5.SOHNUM_0 AND T1.SOPLIN_0 = T5.SOPLIN_0

