/*
目的：
代码所获取的数据是以产品及产品地点为分组条件，获取产品的所有库存数量，所有采购订单数量，所有销售订单数量，所有工单数量。
以方便采购人员对需要采购的物料进行总对总的数据验证
思路：
1.先获取一份完整的物料数据
2.在完整的物料数据上，添加物料的产品地点
3.获取物料的建议类型
4.获取所有事业部下的产品的库存数据，以产品地点分组
5.获取所有事业部下的产品的采购数据，以产品地点分组
6.获取所有事业部下的产品的销售数据，以产品地点分组
7.获取所有事业部下的产品的工单数据，以产品地点分组
8.以上的数量数据均要扣除如已经发货，已经收货等消耗数据
代码中的表解释：
T1:产品物料档案
T2:产品地点档案
T3:本地字典档案
T4:以上三张表的笛卡尔集
T5:库存表
T6:采购订单表
T7:销售订单表
T8:工单组件表
*/

/*
SELECT TOP 100 * FROM ITMMASTER
SELECT TOP 100 * FROM ITMFACILIT
SELECT TOP 100 * FROM ASPLSTD
SELECT TOP 100 * FROM STOCK
SELECT TOP 100 * FROM PORDERQ
SELECT TOP 100 * FROM SORDERQ
SELECT TOP 100 * FROM MFGMAT
*/

SELECT T4.ITMREF_0 N'产品编码',
		T4.STOFCY_0 N'产品地点',
		T4.ITMDES1_0 N'产品名称',
		T4.STU_0 N'产品单位',
		T4.LANMES_0 N'产品属性',
		ISNULL(T5.STOQTY_0,0) N'产品库存',
		ISNULL(T6.POHQTY_0,0) N'预计入库量',
		ISNULL(T7.SALQTY_0,0) N'销售需求量',
		ISNULL(T8.MFGQTY_0,0) N'工单需求量',
		(CASE WHEN (ISNULL(T5.STOQTY_0,0) - (ISNULL(T7.SALQTY_0,0) + ISNULL(T8.MFGQTY_0,0)))> 0 
			  THEN 0 
			  ELSE (ISNULL(T5.STOQTY_0,0) - ((ISNULL(T7.SALQTY_0,0) + ISNULL(T8.MFGQTY_0,0))))
			  END) N'短缺'
FROM (SELECT T1.ITMREF_0,
				T2.STOFCY_0,
				T1.STU_0,
				T1.ITMDES1_0,
				T3.LANMES_0
		FROM ITMMASTER T1 
			LEFT JOIN ITMFACILIT T2 ON T1.ITMREF_0 = T2.ITMREF_0
			LEFT JOIN (SELECT LANMES_0,LANNUM_0 FROM APLSTD WHERE LANCHP_0 = 250 AND LAN_0 = N'CHI') T3 ON T2.REOCOD_0 = T3.LANNUM_0) T4
	LEFT JOIN (SELECT ITMREF_0,STOFCY_0,SUM(QTYPCU_0) STOQTY_0 FROM STOCK GROUP BY ITMREF_0,STOFCY_0) T5 ON T4.ITMREF_0 = T5.ITMREF_0 AND T4.STOFCY_0 = T5.STOFCY_0
	LEFT JOIN (SELECT ITMREF_0,POHFCY_0,SUM(QTYUOM_0 - IIF(RCPQTYSTU_0 > QTYUOM_0, QTYUOM_0,RCPQTYSTU_0)) POHQTY_0 FROM PORDERQ WHERE LINSTA_0 <> 3 GROUP BY ITMREF_0,POHFCY_0) T6 ON T4.ITMREF_0 = T6.ITMREF_0 AND T4.STOFCY_0 = T6.POHFCY_0
	LEFT JOIN (SELECT ITMREF_0,SALFCY_0,SUM(QTY_0 - DLVQTY_0) SALQTY_0 FROM SORDERQ GROUP BY ITMREF_0,SALFCY_0) T7 ON T4.ITMREF_0 = T7.ITMREF_0 AND T4.STOFCY_0 = T7.SALFCY_0
	LEFT JOIN (SELECT ITMREF_0,MFGFCY_0,SUM(RETQTY_0) MFGQTY_0 FROM MFGMAT GROUP BY ITMREF_0,MFGFCY_0) T8 ON T4.ITMREF_0 = T8.ITMREF_0 AND T4.STOFCY_0 = T8.MFGFCY_0
WHERE T4.ITMREF_0 = 'IZN7008'
ORDER BY T4.ITMREF_0,T4.STOFCY_0









