-- SELECT TOP 100 * FROM SORDERQ
-- SELECT TOP 100 * FROM SORDER
-- SELECT TOP 100 * FROM SORDERP


	SELECT (CASE T2.ORDSTA_0 WHEN N'2' THEN N'Y' ELSE N'N' END) AS N'订单关闭',
			(CASE T1.SOQSTA_0 WHEN N'3' THEN N'Y' ELSE N'N' END) AS N'行关闭',
			T1.CREDAT_0 AS N'制单日期',
			T1.SOHNUM_0 AS N'销售订单号',
			T2.BPDNAM_0 AS N'客户名称',
			T1.ITMREF_0 AS N'产品代码',
			T3.ITMDES_0 AS N'产品名称',
			T1.QTY_0 AS N'数量',
			(CASE T2.CUR_0 WHEN N'CNY' THEN T3.GROPRI_0  / 1.17 ELSE T3.GROPRI_0 END) AS N'未税单价',
			(CASE T2.CUR_0 WHEN N'CNY' THEN T1.QTY_0 * T3.GROPRI_0 / 1.17 ELSE T1.QTY_0 * T3.GROPRI_0 END) AS N'未税金额',
			T3.GROPRI_0 AS N'含税单价',
			T1.QTY_0 * T3.GROPRI_0 AS N'含税金额',
			T2.CUR_0 AS N'币种',
			(CASE T2.REP_0 WHEN N'D003' THEN N'甘甜' END) AS N'业务员',
			T3.STU_0 AS N'单位',
			T1.ZRMK_0 AS N'备注',
			T1.CREUSR_0
	FROM SORDERQ T1
		LEFT JOIN SORDER T2 ON T1.SOHNUM_0 = T2.SOHNUM_0
		LEFT JOIN SORDERP T3 ON T1.SOHNUM_0 = T3.SOHNUM_0 AND T1.SOPLIN_0 = T3.SOPLIN_0
	WHERE T2.REP_0 = N'D003' 
	UNION
	SELECT (CASE T2.ORDSTA_0 WHEN N'2' THEN N'Y' ELSE N'N' END) AS N'订单关闭',
			(CASE T1.SOQSTA_0 WHEN N'3' THEN N'Y' ELSE N'N' END) AS N'行关闭',
			T1.CREDAT_0 AS N'制单日期',
			T1.SOHNUM_0 AS N'销售订单号',
			T2.BPDNAM_0 AS N'客户名称',
			T1.ITMREF_0 AS N'产品代码',
			T3.ITMDES_0 AS N'产品名称',
			T1.QTY_0 AS N'数量',
			(CASE T2.CUR_0 WHEN N'CNY' THEN T3.GROPRI_0  / 1.17 ELSE T3.GROPRI_0 END) AS N'未税单价',
			(CASE T2.CUR_0 WHEN N'CNY' THEN T1.QTY_0 * T3.GROPRI_0 / 1.17 ELSE T1.QTY_0 * T3.GROPRI_0 END) AS N'未税金额',
			T3.GROPRI_0 AS N'含税单价',
			T1.QTY_0 * T3.GROPRI_0 AS N'含税金额',
			T2.CUR_0 AS N'币种',
			(CASE T2.REP_0 WHEN N'D003' THEN N'甘甜' END) AS N'业务员',
			T3.STU_0 AS N'单位',
			T1.ZRMK_0 AS N'备注',
			T1.CREUSR_0
	FROM SORDERQ T1
		LEFT JOIN SORDER T2 ON T1.SOHNUM_0 = T2.SOHNUM_0
		LEFT JOIN SORDERP T3 ON T1.SOHNUM_0 = T3.SOHNUM_0 AND T1.SOPLIN_0 = T3.SOPLIN_0
	WHERE T2.CREUSR_0 = N'0031' 
	ORDER BY T1.SOHNUM_0
