--SELECT * FROM SDELIVERY
--SELECT * FROM SDELIVERYD
--SELECT * FROM SINVOICED
--SELECT * FROM TABRATVAT




SELECT T1.CREDAT_0 N'发货日期',
		T1.SDHNUM_0 N'发货单号',
		T1.SOHNUM_0 N'销售单号',
		T1.ITMREF_0 N'产品编码',
		T1.ITMDES_0 N'产品名称',
		T1.QTY_0 N'发货数量',
		T5.GROPRI_0,
		T5.GROPRI_0 N'含税单价',
		T1.QTY_0 * T5.GROPRI_0 N'含税金额'
FROM SDELIVERYD T1
	LEFT JOIN SDELIVERY T2 ON T1.SDHNUM_0 = T2.SDHNUM_0
	LEFT JOIN SINVOICED T3 ON T1.SOHNUM_0 = T3.SOHNUM_0 AND T1.SOPLIN_0 = T3.SOPLIN_0
	LEFT JOIN SORDERP T5 ON T1.SOHNUM_0 = T5.SOHNUM_0 AND T1.SOPLIN_0 = T5.SOPLIN_0
WHERE T2.BPCORD_0 = N'CHN-SH-4465'
	AND T3.NUM_0 IS NULL
ORDER BY T1.SDHNUM_0




















