 --SELECT 
	--	"MFGMATTRK"."USEQTY_0", 
	--	"MFGMAT"."MFGNUM_0", 
	--	"MFGMAT"."BOMSEQ_0",
	--	"ZMMT"."MFGTRKNUM_0",
	--	"MFGITM"."EXTQTY_0",
	--	"MFGITM"."ITMREF_0", 
	--	"ZMMT"."MFGNUM_0", 
	--	"ZMMT"."MFGFCY_0", 
	--	"MFGITM"."MFGLIN_0",
	--	"ITMMASTER"."ITMREF_0", 
	--	"ITMMASTER"."ITMDES1_0", 
	--	"MFGMATTRK"."STU_0", 
	--	"MFGMAT"."USEQTY_0", 
	--	"MFGMAT"."RETQTY_0" 
	--	"ZSOYN"."SOHNUM_0", 
	--	"ZSOYN"."XSOHNUM_0", 
	--	"ZSOYN"."BPCORD_0", 
	--	"ZSOYN"."BPCNAM_0",
	--	"ZSOYN"."ZRMK_0",
	--	"MFGMATTRK"."IPTDAT_0", 
	--	"ZSOYN_1"."XSOHNUM_0",
	--	"ZSOYN_1"."BPCORD_0", 
	--	"ZSOYN_1"."BPCNAM_0", 
	--	"ZSOYN_1"."ZRMK_0"
 --FROM   ((((("x3v7sql"."INNO"."ZMMT" "ZMMT" 
	--	INNER JOIN "x3v7sql"."INNO"."MFGITM" "MFGITM" ON "ZMMT"."MFGNUM_0"="MFGITM"."MFGNUM_0") 
	--	LEFT OUTER JOIN "x3v7sql"."INNO"."MFGMAT" "MFGMAT" ON "ZMMT"."MFGNUM_0"="MFGMAT"."MFGNUM_0") ))) 
	--	LEFT OUTER JOIN "x3v7sql"."INNO"."ZSOYN" "ZSOYN" ON ("MFGITM"."VCRNUMORI_0"="ZSOYN"."SOHNUM_0") AND ("MFGITM"."VCRLINORI_0"="ZSOYN"."SOPLIN_0")) 
	--	LEFT OUTER JOIN "x3v7sql"."INNO"."ZSOYN1" "ZSOYN_1" ON ("MFGITM"."VCRNUMORI_0"="ZSOYN_1"."XSOHNUM_0") AND ("MFGITM"."VCRLINORI_0"="ZSOYN_1"."XSOPLIN_0")) 
	--	LEFT OUTER JOIN "x3v7sql"."INNO"."MFGMATTRK" "MFGMATTRK" ON (("MFGMAT"."MFGNUM_0"="MFGMATTRK"."MFGNUM_0") AND ("MFGMAT"."BOMSEQ_0"="MFGMATTRK"."BOMSEQ_0")) AND ("MFGMAT"."ITMREF_0"="MFGMATTRK"."ITMREF_0")) 
	--	LEFT OUTER JOIN "x3v7sql"."INNO"."ITMMASTER" "ITMMASTER" ON "MFGMAT"."ITMREF_0"="ITMMASTER"."ITMREF_0"
 --WHERE  "ZMMT"."MFGTRKNUM_0"=N'0203MTK17070882' 
	--	AND "ZMMT"."MFGFCY_0"=N'0203' 
	--	AND "MFGITM"."MFGLIN_0"=1000 
	--	AND ("MFGMATTRK"."IPTDAT_0">={ts '2017-07-01 00:00:00'} 
	--	AND "MFGMATTRK"."IPTDAT_0"<{ts '2017-07-14 00:00:00'})
 --ORDER BY "ZMMT"."MFGTRKNUM_0", "MFGMAT"."MFGNUM_0", "MFGMAT"."BOMSEQ_0"





 SELECT T1.MFGTRKNUM_0,
		T1.ITMREF_0,
		T2.ITMDES1_0,
		(T4.RETQTY_0 / T3.EXTQTY_0) LIKQTY_0,
		T4.RETQTY_0,
		ISNULL(T1.USEQTY_0,0) QTY_0,
		T2.STU_0,
		T4.USEQTY_0,
		T1.MFGNUM_0,
		T1.MFGFCY_0,
		T1.IPTDAT_0,
		T3.ITMREF_0,
		T3.EXTQTY_0,
		T5.ZRMK_0,
		T5.BPCORD_0,
		T5.BPCNAM_0,
		T6.BPCORD_0,
		T6.BPCNAM_0,
		T6.ZRMK_0,
		T6.XSOHNUM_0,
		T5.XSOHNUM_0,
		T5.SOHNUM_0,
		T6.SOHNUM_0
 FROM MFGMATTRK T1
	LEFT JOIN ITMMASTER T2 ON T1.ITMREF_0 = T2.ITMREF_0
	LEFT JOIN MFGITM T3 ON T1.MFGNUM_0 = T3.MFGNUM_0 AND T3.MFGLIN_0 = 1000
	LEFT JOIN MFGMAT T4 ON T1.MFGNUM_0= T4.MFGNUM_0
							AND T1.MFGLIN_0 = T4.MFGLIN_0
							AND T1.ITMREF_0 = T4.ITMREF_0
							AND T1.BOMSEQ_0 = T4.BOMSEQ_0
	LEFT JOIN ZSOYN T5 ON T3.VCRNUMORI_0 = T5.SOHNUM_0
							AND T3.VCRLINORI_0 = T5.SOPLIN_0
	LEFT JOIN ZSOYN1 T6 ON T3.VCRNUMORI_0 = T6.XSOHNUM_0
							AND T3.VCRLINORI_0 = T6.XSOPLIN_0
 WHERE T1.MFGTRKNUM_0 = '0202MTK17071433'