


--SELECT TOP 100 * FROM SORDERQ
--SELECT TOP 100 * FROM PORDERQ

--SELECT T2.BPCORD_0 N'客户编码',
--		T3.BPCNAM_0 N'客户名称',
--		T1.SOHNUM_0 N'销售单号',
--		T1.CREDAT_0 N'制单日期',
--		T7.FCYSHO_0 N'事业部',
--		T4.LINOCNNUM_0 N'事业部单号',
--		T8.LANMES_0 N'产品属性',
--		T1.ITMREF_0 N'产品编码',
--		T6.ITMDES1_0 N'产品名称',
--		(CASE T5.REOCOD_0 WHEN 3 THEN 0 ELSE T1.QTY_0 END) N'数量',
--		T1.DEMDLVDAT_0 N'交货日期',
--		T1.ZCUSNUM_0 N'客户单号',
--		T1.ZRMK_0 N'备注',
--		T2.ZREMARK_0 N'参考'
--FROM SORDERQ T1
--	LEFT JOIN SORDER T2 ON T1.SOHNUM_0 = T2.SOHNUM_0
--	LEFT JOIN BPCUSTOMER T3 ON T2.BPCORD_0 = T3.BPCNUM_0
--	LEFT JOIN PORDERQ T4 ON T1.SOHNUM_0 = T4.SOHNUM_0 AND T1.SOPLIN_0 = T4.SOPLIN_0
--	LEFT JOIN ITMFACILIT T5 ON T1.SALFCY_0 = T5.STOFCY_0 AND T1.ITMREF_0 = T5.ITMREF_0
--	LEFT JOIN ITMMASTER T6 ON T1.ITMREF_0 = T6.ITMREF_0
--	LEFT JOIN (SELECT FCY_0,FCYSHO_0 FROM FACILITY) T7 ON T1.SALFCY_0 = T7.FCY_0
--	LEFT JOIN (SELECT LANMES_0,LANNUM_0 FROM APLSTD WHERE LANCHP_0 = 250 AND LAN_0 = N'CHI') T8 ON T5.REOCOD_0 = T8.LANNUM_0
--	LEFT JOIN (SELECT * FROM SORDERQ) T9 ON T4.POHNUM_0 = T9.FMINUM_0 AND T4.SOPLIN_0 = T9.FMILIN_0
--WHERE T1.SALFCY_0 <> '0101'
--	AND T4.LINOCNNUM_0 IS NOT NULL

SELECT * FROM SORDERQ

























