-- SELECT * FROM PRECEIPTD
-- SELECT * FROM PRECEIPT
-- SELECT * FROM PINVOICED
-- SELECT * FROM PRETURND


SELECT T1.PTHNUM_0 N'收货单号',
		T1.POHNUM_0 N'订单号',
		T2.BPONAM_0 N'供应商名称',
		T1.CREDAT_0 N'收货日期',
		T1.STU_0 N'单位',
		T1.ITMREF_0 N'产品代码',
		T1.ITMDES_0 N'产品名称',
		T1.QTYUOM_0 N'收货数量',
		T4.QTYUOM_0 N'开票数量',
		T5.QTYUOM_0 N'退货数量',
		T1.QTYUOM_0 - T4.QTYUOM_0 N'未开票数量',
		T1.NETCUR_0 N'货币',
		T1.GROPRI_0 N'无税单价',
		T1.GROPRI_0 * T1.QTYUOM_0 N'无税金额',
		T1.GROPRI_0 * 1.17 N'含税单价',
		T1.GROPRI_0 * T1.QTYUOM_0 * 1.17 N'含税金额',
		(CASE T6.STA_0 WHEN 1 THEN N'待处理' WHEN 2 THEN N'待处理' WHEN 3 THEN N'待处理' END) N'发票状态',
		T3.NOMUSR_0 N'制单人'
FROM PRECEIPTD T1
	LEFT JOIN PRECEIPT T2 ON T1.PTHNUM_0 = T2.PTHNUM_0
	LEFT JOIN AUTILIS T3 ON T1.CREUSR_0 = T3.USR_0
	LEFT JOIN PINVOICED T4 ON T1.PTHNUM_0 = T4.NUMORI_0 AND T1.PTDLIN_0 = T4.LINORI_0
	LEFT JOIN PRETURND T5 ON T1.PTHNUM_0 = T5.PTHNUM_0 AND T1.PTDLIN_0 = T5.PTDLIN_0
	LEFT JOIN PINVOICE	T6 ON T4.NUM_0 = T6.NUM_0
WHERE T1.POHFCY_0 = N'0203'
ORDER BY T1.PTHNUM_0