--SELECT IDENT1_0,IDENT2_0,TEXTE_0 FROM ATEXTRA WHERE CODFIC_0 = N'TABLOCTYP' AND LANGUE_0 = N'CHI' AND ZONE_0 = N'TYPDESAXX'
--SELECT TOP 100 * FROM STOJOU
--SELECT * FROM FACILITY


SELECT  T1.ITMREF_0 N'产品编码',
		T6.FCYSHO_0 N'事业部',
		T3.ITMDES1_0 N'产品名称',
		T1.LOT_0 N'批次号',
		T1.BPRNUM_0 N'供应商编码',
		T5.BPRNAM_0 N'供应商名称',
		T1.LOC_0 N'库位编码',
		T2.TEXTE_0 N'库位名称',
		T1.VCRNUM_0 N'单号',
		T1.VCRNUMORI_0 N'来源单号',
		T1.STU_0 N'单位',
		T1.QTYSTU_0 N'数量',
		T1.AMTORD_0 N'金额',
		T1.STA_0 N'状态',
		--T4.NOMUSR_0 N'制单人',
		T1.CREDAT_0 N'制单日期'
FROM STOJOU T1
	LEFT JOIN (SELECT IDENT1_0,IDENT2_0,TEXTE_0 FROM ATEXTRA WHERE CODFIC_0 = N'TABLOCTYP' AND LANGUE_0 = N'CHI' AND ZONE_0 = N'TYPDESAXX') T2 ON T1.LOC_0 = T2.IDENT2_0 AND T1.STOFCY_0 = T2.IDENT1_0
	LEFT JOIN (SELECT ITMREF_0,ITMDES1_0 FROM ITMMASTER) T3 ON T1.ITMREF_0 = T3.ITMREF_0
	LEFT JOIN (SELECT USR_0,NOMUSR_0 FROM AUTILIS) T4 ON T1.CREUSR_0 = T4.USR_0
	LEFT JOIN (SELECT BPRNUM_0,BPRNAM_0 FROM BPARTNER) T5 ON T1.BPRNUM_0 = T5.BPRNUM_0
	LEFT JOIN (SELECT FCY_0,FCYSHO_0 FROM FACILITY) T6 ON T1.STOFCY_0 = T6.FCY_0
WHERE T1.VCRNUMORI_0 <> ''
	AND T1.VCRNUM_0 <> '' 
	AND T1.BPRNUM_0 <> '' 
	AND T1.BPRNUM_0 NOT LIKE N'YN-%'
	AND (T1.VCRNUM_0 LIKE N'%PRH%' OR T1.VCRNUM_0 LIKE N'%REC%')
ORDER BY T1.ITMREF_0,T1.STOFCY_0,T1.CREDAT_0



