SELECT * FROM STOJOU WHERE ITMREF_0 = 'ICU9003-08'

-- SELECT TOP 10 * FROM SINVOICED
-- SELECT TOP 10 * FROM SINVOICE
-- SELECT TOP 10 * FROM XINVOICER
-- SELECT * FROM SINVOICED
-- SELECT * FROM SINVOICE
-- SELECT * FROM TABVAT


SELECT TOP 100 T1.NUM_0 AS N'发票号',
		T1.SOHNUM_0 AS N'销售订单号',
		T1.SDHNUM_0 AS N'发货单号',
		T2.XGTAXNUM_0 AS N'专用发票代码',
		T3.BPYNAM_0 AS N'销货单位',
		T1.ITMDES1_0 AS N'货物（劳务）名称',
		T1.ITMREF_0 AS N'规格型号',
		T1.STU_0 AS N'单位',
		T1.QTY_0 AS N'数量',
		T1.NETPRINOT_0 AS N'单价',
		T1.AMTNOTLIN_0 AS N'金额',
		T1.RATTAXLIN_0 / 100 AS N'税率',
		T1.AMTTAXLIN_0 AS N'税额'
FROM SINVOICED T1
	LEFT JOIN XINVOICER T2 ON T1.NUM_0 = T2.NUM_0
	LEFT JOIN SINVOICE T3 ON T1.NUM_0 = T3.NUM_0


