-- SELECT * FROM SDELIVERY
-- SELECT * FROM SDELIVERYD
-- SELECT * FROM SORDER
-- SELECT * FROM SORDERP


SELECT T1.CREDAT_0,
		T3.ZCUSNUM_0,
		T1.SDHNUM_0,
		T4.BPCNAM_0,
		T1.SOHNUM_0,
		T4.BPCORD_0,
		T1.ITMREF_0,
		T1.ITMDES1_0,
		T1.STU_0,
		T1.QTY_0,
		T1.GROPRI_0,
		(T1.QTY_0 * T1.GROPRI_0) Total,
		T4.REP_0,
		T3.ZRMK_0
FROM SDELIVERYD T1
	LEFT JOIN SDELIVERY T2 ON T1.SDHNUM_0 = T2.SDHNUM_0
	LEFT JOIN SORDERQ T3 ON T1.SOHNUM_0 = T3.SOHNUM_0 AND T1.SOPLIN_0 = T3.SOPLIN_0
	LEFT JOIN SORDER T4 ON T1.SOHNUM_0 = T4.SOHNUM_0